### ISSUE TITLE
Bug: Microsite admin cannot add 2 or 3 column layouts

### ISSUE THREAD

**Issue by msayoung** [localgovdrupal/localgov_microsites#104]
As a "Microsite Admin" if I add a new Layout section, and try and choose 2 or 3 column layouts I get the  following:

![Image](https://user-images.githubusercontent.com/3852805/170020936-7411e588-de9e-4b2a-8d8f-7e84e3c03cbd.png)

**Comment by ekes** [comment]
Guess it might be this? https://www.drupal.org/project/layout_paragraphs/issues/3166215

Did we fix this somewhere for localgov?

Guess we grant the permission.
