### ISSUE TITLE
"Add content" links sometimes failing.

### ISSUE THREAD

**Issue by finnlewis** [localgovdrupal/localgov_microsites#106]
The 'node add' link sometimes goes to the wrong place.

@ekes points out there is a patch, @stephen-cox says it is not always applying on install.

**Comment by stephen-cox** [comment]
Patch should now be on all council sites. Hadn't been pulled through on the first composer update. Running it again pulled in the patch

**Comment by finnlewis** [comment]
Nice one @stephen-cox , I'll close this, but feel free to re-open if needed.
