### ISSUE TITLE
Collate any existing user research on microsites (Beta phase and/or councils)

### ISSUE THREAD

**Issue by finnlewis** [localgovdrupal/localgov_microsites#11]
We'd like to remind ourselves about the research from Beta phase.

Also, is there research that councils have done that we can add to our knowledge base.

- [ ] Produce a concise summary if evidence and research to date.

**Comment by msayoung** [comment]
Started compiling here: https://docs.google.com/document/d/1NyoZDykiMnjrmaNA35ZQjo9DVnIM7dZqccYo2yDGcjc/edit#

**Comment by msayoung** [comment]
Also on the Miro board: https://miro.com/app/board/uXjVOStMNW8=/?moveToWidget=3458764522657689282&cot=14

**Comment by msayoung** [comment]
@finnlewis were you expecting anything else on this?
