### ISSUE TITLE
Unable to add banner images to page as site admin

### ISSUE THREAD

**Issue by stephen-cox** [localgovdrupal/localgov_microsites#111]

**Comment by stephen-cox** [comment]
Looks like this is because the site admin user doesn't have the `create localgov_page content` permission. Fixing this will either involve adding this permission, which allows them to do too much, or using Group Media.

**Comment by stephen-cox** [comment]
Even using Group Media there's a problem with this. Group checks permissions using the route and this doesn't work when on a domain.

Will need to add a hook to check permissions.

**Comment by ekes** [comment]
It should be the same for creating a node in a group no matter the domain? The path should be the same - within the group, never /node/add/type but /group/1/....content:node or whatever it is.

**Comment by stephen-cox** [comment]
Not sure what's different between creating and editing a node in terms of the permissions check, but one works and one doesn't.

The node_micro module did something similar as this PR here https://www.drupal.org/project/micro_node/issues/3100098

**Comment by ekes** [comment]
Right so it probably doesn't work on the control domain, nor the microsite domain? I'm assuming then if a user without create permission is on the control domain and adding content to the site it also doesn't work. Which will probably be a larger group problem with media.

An issue that the permissions check is being run on some submission of the form before the entity is saved or something?
