### ISSUE TITLE
allow (someone) to decide which content types are available on a microsite (permissions)

### ISSUE THREAD

**Issue by msayoung** [localgovdrupal/localgov_microsites#120]
## User story: 

As a microsite controller 
I want to restrict access to specific content types to a given microsite.
So that we can prevent content designers from creating superfluous content / reduce noise on content creation  - and hide the search block

## Notes

This will result in extending options for each microsite.
So on each microsite , we'll have checkboxes for 
 - each content typer
 - search enabled
 - etc...

We'll follow up with other permissions implementations later. 

## Acceptance tests:

1. Log in to control site as microsite controller.
2. Edit microsite 1 settings
3. Enable or disable each content type
4. Log into microsite as a microsite admin
5. Confirm that I can (or can't) create each content type.
6. As microsite admin, enable events on my microsite
7. Be able to create (and see) events.
8. See automated tests to cover this!

Note: 
 - we will need to address the /events page
 - we will need to address the /news
 - if we remove the permission for events, previous events created will no longer be visible.
 - we will need automated tests for this! (ties in with tests for g-invite)

**Comment by msayoung** [comment]
I think we decided in the WG that the following is more accurate:

As a microsite admin
I want to restrict access to specific content types available to a _microsite editor_
So that we can prevent content designers from creating superfluous content / reduce noise on content creation 

@finnlewis is this also your understanding?

**Comment by msayoung** [comment]
I think we decided in the WG that the following is more accurate:

As a microsite admin
I want to restrict access to specific content types available to a _microsite editor_
So that we can prevent content designers from creating superfluous content / reduce noise on content creation

**Comment by finnlewis** [comment]
@ekes 
Trying to demo this, the form to select each content types does not always save.
The first submission seems to work, but then the site name gets removed from the other tab, preventing further sumbissions.
 
@stephen-cox can you add your notes too ?

**Comment by ekes** [comment]
[#188](https://github.com/localgovdrupal/localgov_microsites_group/pull/188) fixed this?

**Comment by ekes** [comment]
Done.
