### ISSUE TITLE
Review labelling and signposting

### ISSUE THREAD

**Issue by finnlewis** [localgovdrupal/localgov_microsites#121]
From user testing report 

Users have varying abilities and experience. We should cater for all levels of experience. 

- [ ] Review labels 
- [ ] guides / tours
- [ ] help text

### /admin/microsites
/admin/microsites/add/microsite
Status message after new site creation
/group/1/members
etc etc

Questions to consider
- What base line level of experience  / understanding do we want

**Comment by willguv** [comment]
Let's include a final review of labelling as part of the release plan

**Comment by msayoung** [comment]
Closing this as have a more comprehensive ticket here: https://github.com/localgovdrupal/localgov_microsites_group/issues/269
