### ISSUE TITLE
Simplify layout options for layout paragraphs

### ISSUE THREAD

**Issue by msayoung** [localgovdrupal/localgov_microsites#123]
What should the default layouts be? 
Should they be sections to build up or full page layouts? 
Simpler or more complex?

- [x] full width sections from 2 and 3 column layouts
- [x] Recreate dummy content so they can still be edited

**Comment by finnlewis** [comment]
See https://www.drupal.org/docs/drupal-apis/layout-api/how-to-register-layouts

**Comment by msayoung** [comment]
In the end I didnt know whether it better to be in localgov_page https://github.com/localgovdrupal/localgov_page/pull/7
or localgov_paragraphs_microsite https://github.com/localgovdrupal/localgov_paragraphs/pull/52

localgov_page is where we define which layouts the page is using https://github.com/localgovdrupal/localgov_page/pull/7/commits/300a6e224a7f7778b20b3d838afbe402f8dd3b1f
so maybe there after all. 

@finnlewis @stephen-cox thoughts?

**Comment by msayoung** [comment]
@finnlewis thinks this should live in localgov_paragraphs_microsite

@stephen-cox or @ekes - if you think something else, please holler.

**Comment by stephen-cox** [comment]
The problem with putting them in localgov_paragraph_microsites is you are creating a dependency between localgov_page and localgov_paragraph_microsites with this: https://github.com/localgovdrupal/localgov_page/pull/7/files#diff-1dc92900e6604616be259d97e4d671cc12264a99283c256b73a08b07233848bb

My suggestion is to either put this in localgov_paragraphs or a new localgov_paragraphs_layout module

**Comment by msayoung** [comment]
This is breaking my mind. 

Given that localgov_page is paragraph enabled, which paragraphs are we ok to be dependent on? 

Asking also because I'm creating some new paragraphs to add the mix, and though their configuration can live elsewhere, adding them to the localgov_page content field has to happen somewhere...

**Comment by finnlewis** [comment]
I'm up for putting everything in localgov_paragraphs and having that as the main dependency, then just enabling the paragraphs we want in each use case such as localgov_page.

**Comment by finnlewis** [comment]
Brief discussion in sprint planning: 
 - we could move all paragraphs into localgov_paragraphs for now
 - then move paragraphs into sub-modules based on complexity and dependencies and use cases to keep things somewhat modular. 

Things that might break:
 - anything with paths or namespaces (like what?)
 - tabs and accordion have javascript - clearing cache should re-discover moved libraries
 - templates should also be rediscovered

Then, on the localgov_page field, we select the paragraphs we want on the layout paragraph field config,.

**Comment by msayoung** [comment]
This is done at last, closing
