### ISSUE TITLE
Streamline "create new page section" form - remove admin fieldset

### ISSUE THREAD

**Issue by msayoung** [localgovdrupal/localgov_microsites#124]
![Image](https://user-images.githubusercontent.com/3852805/172633880-15dcfd62-fba5-4fae-bb48-263dc0b690b3.png)

**Comment by msayoung** [comment]
@stephen-cox it wasn't obvious where to go about this. any ideas?

**Comment by stephen-cox** [comment]
PR for this here https://github.com/localgovdrupal/localgov_page/pull/8, but maybe this should be moved to a paragraphs module along with https://github.com/localgovdrupal/localgov_page/pull/7
