### ISSUE TITLE
Streamline admin screens for creating microsites

### ISSUE THREAD

**Issue by msayoung** [localgovdrupal/localgov_microsites#125]
### Admininstration screen (where a microsite controller lands on log in)

![Image](https://user-images.githubusercontent.com/3852805/172611992-851ba4c2-0d58-49f1-a4de-200f194f1b94.png)

- [x] Add a description to the Microsites item
- [x] Hide Tools and Structure on the page (as they have nothing in them)
- [x] Hide Structure in the menu 
- [x] Move Microsites to the top of the list

Question: The Index tab - do we want it? 

### Create a new Microsite screen

![Image](https://user-images.githubusercontent.com/3852805/172612462-7554a198-86e0-4a93-a892-b433f380227d.png)

- [x] Remove Site name and slogan fields
- [x] Remove error pages
- [ ] Improve description on Domain status
- [x] Rename Email address to Site email address

web/modules/contrib/domain_group/src/Plugin/DomainGroupSettings/GroupDomain.php

**Comment by msayoung** [comment]
Needs definition

**Comment by msayoung** [comment]
@finnlewis @stephen-cox - can you review the above and let me know if there are serious concerns with the above

**Comment by finnlewis** [comment]
Looks like a reasonable set of tasks!

**Comment by msayoung** [comment]
https://github.com/localgovdrupal/localgov_microsites_group/pull/99

**Comment by stephen-cox** [comment]
@msayoung I have created a PR to hide unused menu items: https://github.com/localgovdrupal/localgov_microsites/pull/141

I've also updated the PR you created to remove / update some of the fields mentioned here.

I'm not site what to do with the `Domain status' field. At the moment, on Drupal user 1 has permission to access to "Inactive" sites. It can be used for "unpublished" or "internal" sites. In which case we need to set the appropriate roles permissions. Or we can remove it and make all sites active. For the former I suggest creating a new issue for this as we need to specify who should have access and the wording to go with it.

**Comment by msayoung** [comment]
Beautiful @stephen-cox !
