### ISSUE TITLE
Streamline admin screens for creating users

### ISSUE THREAD

**Issue by msayoung** [localgovdrupal/localgov_microsites#126]
![Image](https://user-images.githubusercontent.com/3852805/172631980-78e616df-6acd-47d2-8202-44e6a532e6e5.png)

can we hide the locale settings?

**Comment by finnlewis** [comment]
Assuming we're still going via this form, seems good to hide the locale / the time zone for now.

**Comment by msayoung** [comment]
I think we don't need this anymore. closing
