### ISSUE TITLE
Review cropping and image handling

### ISSUE THREAD

**Issue by msayoung** [localgovdrupal/localgov_microsites#128]
Banner image on content page
Footer banner image
Header logo 
Footer logos

Paragraph image fields

**Comment by finnlewis** [comment]
"We need a strategy!", @msayoung

**Comment by msayoung** [comment]
We're suggesting the a microsite admin can set some image style globally per microsite for

## Global
Teaser images
- square, 4:3, 3:2, 7:3

## Contextual

Featured teaser image 
- Add field card or teaser option 
- Add image style (square, 4:3, 3:2, 7:3)

media with teaser image
- Add image style (square, 4:3, 3:2, 7:3)

header logo
- help text

footer logos
- set image style ( 85 x 200 )

**Comment by msayoung** [comment]
We have a plan and all the things got split in to tickets

Create an image style for footer logos:
https://github.com/localgovdrupal/localgov_microsites_group/issues/123

Allow admins to global set an image style for teasers:
https://github.com/localgovdrupal/localgov_microsites_group/pull/121

Image styles on paragraphs: https://github.com/localgovdrupal/localgov_paragraphs/issues/57
