### ISSUE TITLE
Site design UI: Combine content and design tabs

### ISSUE THREAD

**Issue by msayoung** [localgovdrupal/localgov_microsites#129]
Suggestion to combine 

- Header design and Header content tab
- Footer design and Footer content tab

**Comment by msayoung** [comment]
@markconroy @richard-s-rowley this good with you ?

**Comment by markconroy** [comment]
Good with me +1

**Comment by msayoung** [comment]
https://github.com/localgovdrupal/localgov_microsites_group/pull/99
