### ISSUE TITLE
Finalise User testing report

### ISSUE THREAD

**Issue by finnlewis** [localgovdrupal/localgov_microsites#133]
Finalise the existing report slide deck: 

- [ ] credit everyone
- [ ] add pics if possible
- [ ] flag how much fun it was

**Comment by finnlewis** [comment]
@msayoung suggested maybe re-recording snippets on Loom (https://www.loom.com/) to replay specific issues.

**Comment by finnlewis** [comment]
@stephlenz do you happen to know if the user testing report is finalised?

**Comment by msayoung** [comment]
From @stephlenz 

i think the report itself has been finished, but rae and i are going to be recording a video to walk through the user tester's journeys and issues so far to summarise it nicely

we're schedule to record on thursday - here's the "script" we're going to follow if you have anything you want to add to it/change feel free to amend the doc: https://docs.google.com/document/d/1tbfzYaRxIEuXA_grwfdNXGwIlZFHocQHS448nKCU8bg/edit#

**Comment by finnlewis** [comment]
Great, thanks @msayoung and @stephlenz !

**Comment by msayoung** [comment]
I've added the video to the user testing report https://docs.google.com/presentation/d/1SnZFJW0olU-Z4-lfA10qIVuIJxZT91mAMh5ChP6r6h8/edit#slide=id.g13b99cf0cfd_0_0

@finnlewis @richard-s-rowley can we call this done now?

**Comment by finnlewis** [comment]
Yes! Thanks everyone - love the video!
