### ISSUE TITLE
Colour picker tweaks

### ISSUE THREAD

**Issue by msayoung** [localgovdrupal/localgov_microsites#134]
![Image](https://user-images.githubusercontent.com/3852805/172396438-6d9db96b-0b5a-4573-9129-fa597d5a04c4.png)

### Problem 1
In user testing people assumed that black was the default colour when selecting colour, as the swatch always shows black. 

I did wonder whether we can set the input type to `default=" "` which might show no colour swatch but I discover this is impossible with the `input type="color"` ... more thought needed. 

### Problem 2
You cannot pick black without first selecting another colour

**Comment by markconroy** [comment]
Hi @msayoung 

Can you check this for an approach? https://github.com/localgovdrupal/localgov_microsites_colour_picker_fields/pull/4

**Comment by finnlewis** [comment]
@markconroy - we put a 1 and a 21 on this as we were not sure of the size of this... care to update the points?

**Comment by markconroy** [comment]
I've updated it to `3`, but will admit I still (a year later) don't understand story points.
