### ISSUE TITLE
Site design > Header content: site name and site slogan

### ISSUE THREAD

**Issue by msayoung** [localgovdrupal/localgov_microsites#140]
Site name and site slogan are requested at various stages of the journey. 
On site set up, on site configuration and again in the header content. 

### Question
Who should be able to alter the site name and site slogan (controller, admin, editor?)
Should the site slogan and site name in the header be able to be set independently to the main site slogan and site name?

### potential solution?

Site name and slogan to be set in the site settings
Toggle on/off the appearance of these elements in the header.

**Comment by willguv** [comment]
@msayoung is this covered already? If not, should be fixed/ closed in 11/12

**Comment by msayoung** [comment]
This is done

https://github.com/localgovdrupal/localgov_microsites_group/pull/239
