### ISSUE TITLE
Add Rae and Steph to Github and Slack

### ISSUE THREAD

**Issue by finnlewis** [localgovdrupal/localgov_microsites#142]

**Comment by finnlewis** [comment]
Hi @stephlenz and @RaePatel - hopefully you've both got access to the project board at https://github.com/orgs/localgovdrupal/projects/21/views/2 and to the LocalGov Drupal Slack channel now! 

Welcome aboard! 

Let us know if not. 

:)

**Comment by stephlenz** [comment]
Yep! I can see it :)
