### ISSUE TITLE
Font options in UI

### ISSUE THREAD

**Issue by richard-s-rowley** [localgovdrupal/localgov_microsites#143]
Changes to the list of fonts available to admins

**Comment by richard-s-rowley** [comment]
1. Remove the following from the list of body fonts (keep in heading options):
Archivo Black
Archivo Narrow
Sporting Grotesk
Playfair display

2. Order fonts alphabetically

3. Add two more fonts, available in both body and heading lists:
- Inter
- Lora

**Comment by msayoung** [comment]
I've added the font options, but still need to add the actual fonts to the theme

**Comment by msayoung** [comment]
MR: https://github.com/localgovdrupal/localgov_microsites_base/pull/43
