### ISSUE TITLE
Create `microsite admin` role

### ISSUE THREAD

**Issue by stephen-cox** [localgovdrupal/localgov_microsites#144]
We currently need to give authenticated users quite a few permissions to do stuff (create media, manage path aliases, manage directory facets). It's not ideal adding these permissions to the authenticated user role as it prevents the creation of other user types that shouldn't have these permissions.

We should create a new user role (microsite admin?) and assign these sorts of global permissions to them.

@ekes @finnlewis Thoughts on this? Can it be done with group permissions or will there always be a need to assign some global permissions to site admins?

**Comment by stephen-cox** [comment]
Discussed at stand-up. We want to keep away from admin and editor for role labels to avoid confusion. @ekes suggestion is "Microsites Trusted User"

**Comment by msayoung** [comment]
Decided on "Microsite Trusted Editor" in the end
