### ISSUE TITLE
Future headless - are we explicitly architecting this so that councils can evolve to headless later on?

### ISSUE THREAD

**Issue by finnlewis** [localgovdrupal/localgov_microsites#15]

**Comment by msayoung** [comment]
We are currently working on the assumption that not headless for now, but not architecting in a way that rules it out. 

see  [assumptions log ](https://docs.google.com/spreadsheets/d/1LuodNlPglfdCH0VW9mISOkpEG4N3-MhSKaIOgmHO1Ok/edit#gid=0)
