### ISSUE TITLE
Microsite admin cannot set homepage or error pages, site name, slogan and status of microsite

### ISSUE THREAD

**Issue by msayoung** [localgovdrupal/localgov_microsites#157]
## User Story

As a microsite admin
I want to set the microsite site name, site slogan and homepage
So that I can change these when needed. 

## Notes

We might want to check if the 'microsite admin' should be able to change the hostname or not. Coz this could break the internet!
Also, might want to think about custom error pages.

## Acceptance tests: 

1. Log in as microsite admin user to microsite 1
2. See edit 'settings' tab
3. Click 'settings' tab
4. Edit 'site name', 'slogan', 'email address'
5. Change the 'site front page'
6. Save
7. See changes take effect.

**Comment by finnlewis** [comment]
@ekes has started an issue on the domain_group module to swap the plugin from using 'domain site config' to using 'domain config'.

Passing to @ekes to think about

**Comment by ekes** [comment]
So while working on the domain_site_config -> domain_config I'm looking at this form.

It's one form with the domain configuration (domain name, if it is active) and the site configuration (site name, slogan ...)
These are two different entities, and I suspect want two different permissions. Like it's the domain controller's job to set the domain configuration (and the site configuration); but we'd allow the site admin to edit the site configuration?

@msayoung any thoughts on this? In relation to the create, and edit flow that we currently have, and form edits etc.

**Comment by ekes** [comment]
If it helps my current thought is that it might be possible to have them on one form, but from two plugins, where permissions as checked by the plugin.

**Comment by finnlewis** [comment]
Yer, they feel like separate permissions. If it's easy enough to do that and keep them on the same form, that sounds good!

**Comment by ekes** [comment]
PR https://git.drupalcode.org/issue/3278349-3293374/-/merge_requests/1
and 
https://git.drupalcode.org/issue/3278349-3293374/-/merge_requests/1
