### ISSUE TITLE
Breakout layouts

### ISSUE THREAD

**Issue by msayoung** [localgovdrupal/localgov_microsites#160]
When choosing to add a new layout we can decide whether it is constrained, breakout or full width. 

@markconroy suggested using https://www.drupal.org/project/layout_options Layout Options

**Comment by msayoung** [comment]
This is enabled. Needs the newest commits on localgov_base to see it working. 
closing for now.

**Comment by msayoung** [comment]
Reopening. This isn't working on the frontend anymore, though i can't work out why.

**Comment by markconroy** [comment]
This PR should fix it: https://github.com/localgovdrupal/localgov_microsites_base/pull/86

The paragraphs field has changed from 'Page Paragraphs' to 'Localgov Paragraphs'.
