### ISSUE TITLE
Manual test: Logging in

### ISSUE THREAD

**Issue by msayoung** [localgovdrupal/localgov_microsites#161]
- [ ] As Microsite admin X See an error message when I try to log into microsite Y
- [ ] As Microsite admin Y See an error message when I try to log into site X
- [ ] As Microsite admin X Be able to log into site X
- [ ] Microsite admin Y Be able to log into site Y

Confirm the above is true
Suggest changes
Do we need automated tests?

**Comment by finnlewis** [comment]
So... this does not behave exactly as I expected. 

As admin1 assigned to microsiite1 but not microsite 2, I can log in to microsite 2, but I just get access denied as soon as I log in:

![Image](https://user-images.githubusercontent.com/326588/177939984-ed355ef2-fa89-4bdf-a452-c2d27b310045.png)

So the user stories stand up, the user does see an error message. 

I'm OK to mark this as done. 

@stephen-cox @ekes @msayoung there is the question of automated tests. Do we already have any for this? If not is it a valuable use of time to write some to confirm admin1 on site2 gets a 403 access denied after logging in?

**Comment by ekes** [comment]
There are tests for the behaviour your mention. They are in `domain_group` module https://git.drupalcode.org/sandbox/ekes-3278349/-/blob/3.x/tests/src/Functional/UniqueGroupAccessTest.php

I think I had a thing about logging in too in a branch somewhere, it's mindblowing though.
