### ISSUE TITLE
Create a new install profile / distribution for LocalGov Microsites

### ISSUE THREAD

**Issue by finnlewis** [localgovdrupal/localgov_microsites#17]
## User story 

As a developer 

I want to install the LocalGov Drupal Microsites distribution

So that I can start to build and deploy microsites 

## Acceptance tests: 

1. Be able to do a 'composer require localgovdrupal/localgov_microsites_project'
2. Run the install profile
3. Be able to create a microsite.

**Comment by stephen-cox** [comment]
We have a project (https://github.com/localgovdrupal/localgov_microsites_project) and a profile (https://github.com/localgovdrupal/localgov_microsites).

Create a new project with

```shell
composer create-project --stability dev localgovdrupal/localgov_microsites_project MY_PROJECT
```

**Comment by andybroomfield** [comment]
Out of interests, this means the localgov_microsites module will not be part of and get installed by default for main profile?

**Comment by stephen-cox** [comment]
The decision has been to make `localgov_microsites` a Drupal profile, not a module.
