### ISSUE TITLE
Bug: chained classes in menu blocks

### ISSUE THREAD

**Issue by msayoung** [localgovdrupal/localgov_microsites#173]
in the main and utility menus we're getting chained classes

`block-group-content-menulgms-main-menu` `block-group-content-menulgms-utility-menu`

**Comment by markconroy** [comment]
Looks like this is not a bug. In block.html.twig (from localgov_base) we are rendering the following classes:

```
{%
  set classes = [
    'block',
    'block-' ~ configuration.provider|clean_class,
    'block-' ~ plugin_id|clean_class,
  ]
%}
```

If you check what `plugin_id` evaluates to, it will be something like `group_content_menu:lgms_main_menu`. When you apply `|clean_class` to that, you get `group-content-menulgms-main-menu` which is what we are getting which _looks like a chained class_, but actually isn't.

**Comment by msayoung** [comment]
That would be why I couldnt hunt it down! 
Thanks @markconroy 

I'll close this
