### ISSUE TITLE
Footer menu block broken

### ISSUE THREAD

**Issue by msayoung** [localgovdrupal/localgov_microsites#177]

**Comment by msayoung** [comment]
https://github.com/localgovdrupal/localgov_microsites_group/commit/bdc9eb8e2e1cd2e5b3f498b889e1058a904a0873#diff-699039d553d59fc136cd006bfec5d7683a457150d571df5c395c08945d9352a7

@ekes - I _think_ this is when the footer menu block went missing. What's this commit doing and is it obvious how to get the footer menu block back?

**Comment by ekes** [comment]
That removed our hacked replacement block. But the correct block from the module should have the put in its place with https://github.com/localgovdrupal/localgov_microsites_base/pull/55

**Comment by ekes** [comment]
Reading https://github.com/localgovdrupal/localgov_microsites_base/pull/55 the footer wasn't done. So https://github.com/localgovdrupal/localgov_microsites_base/pull/75 does?
