### ISSUE TITLE
Add a custom favicon to the microsite

### ISSUE THREAD

**Issue by msayoung** [localgovdrupal/localgov_microsites#178]
## User story

As a microsite admin
I want to add a custom favicon to the microsite
So that my site is on brand.

## Assumptions: 

 - We'll be uploading a single png file, just like the theme config page in Drupal.
 - Might add better manipulation of favicon files later (16 / 32 / 64 etc.)

**Comment by ekes** [comment]
Additional thoughts/assumptions:

The field probably fits best on the Group Entity (so under Site Design); rather than what would probably have to be another tab on Site Settings (which might be more obvious from a technical backend pattern point of view).

I'm guessing having the item as a File Entity associated with the Group Entity won't do any harm in the long term, maybe help manipulating it even? For now however the file will then be used to override a domain specific site configuration value (as the Site Settings do).

**Comment by ekes** [comment]
https://github.com/localgovdrupal/localgov_microsites_group/tree/feature/178-favicon

This as spec just uses the theme setting favicon as per core, but then varying them per domain. The value is added, I guess by core theme system, in the `head-placeholder`.

The file is uploaded using a file field on the microsite group - and can be removed there. On saving the group the domain configuration override is updated.

Extending for variants could then be done within the theme, and its configuration.

Two questions:
 * Where should the favicon be on the form? It's presently not in a tab, just defaulted to the bottom.
 * How should we remove all the hard coded <link rel="*icon*" ... from the head? While they're there the <link rel="icon" isn't the one browsers are going to pick up. The icons are added in the base of https://github.com/localgovdrupal/localgov_base/blob/1.x/templates/layout/html.html.twig#L42 I'm guessing it's best to make a copy of html.html.twig in the localgov_microsites_base and remove them there? But should the option to upload a custom favicon be removed from the base theme (as it's there and doesn't work now, as it gets overridden).

**Comment by ekes** [comment]
PR for feedback about the two questions before merging: https://github.com/localgovdrupal/localgov_microsites_group/pull/220

**Comment by markconroy** [comment]
Hardcoded favicons links will be fixed by this PR https://github.com/localgovdrupal/localgov_base/pull/279

**Comment by ekes** [comment]
So it's just this question now:-

Where should the favicon be on the form? It's presently not in a tab, just defaulted to the bottom.

@msayoung got an idea where to put it maybe?

**Comment by ekes** [comment]
> Hardcoded favicons links will be fixed by this PR [localgovdrupal/localgov_base#279](https://github.com/localgovdrupal/localgov_base/pull/279)

Do we need to do something else for this is the microsites default theme?

**Comment by markconroy** [comment]
Yes, we'll need a follow-up for favicons in `localgov_microsites_base`.

Here we go: https://github.com/localgovdrupal/localgov_microsites_base/issues/121
