### ISSUE TITLE
Finalise wireframes for the entire MVP frontend

### ISSUE THREAD

**Issue by msayoung** [localgovdrupal/localgov_microsites#18]
- Layouts for content types
- Layouts for lists of things
- Layout for Search (if in MVP)
- Layout for teasers ?

**Comment by finnlewis** [comment]
Hey @richard-s-rowley and @msayoung , could we pop a link to the wireframes on this issue?

**Comment by msayoung** [comment]
https://miro.com/app/board/uXjVO9o1iRk=/

**Comment by finnlewis** [comment]
Keeping open to define testing MVP - what do we hope to test.

**Comment by finnlewis** [comment]
I get the feeling that this has been superseded. Closing, but feel free to re-open if needed.
