### ISSUE TITLE
Refactor localgov_events to have an 'events channel' akin to News

### ISSUE THREAD

**Issue by finnlewis** [localgovdrupal/localgov_microsites#182]
This will be a major change to localgov_events - might need migration paths.

Waltham Forest have already done this, Haringey are interested.

**Comment by msayoung** [comment]
https://github.com/localgovdrupal/localgov_events/issues/54

**Comment by willguv** [comment]
Let's run through changes at Product Group, and likely pick up early next year as BAU

**Comment by msayoung** [comment]
Closing, as this will be dealt with as part of Events. https://github.com/localgovdrupal/localgov_events/issues/54
