### ISSUE TITLE
Event: add layout paragraphs field for fun layouts and lots of paragraph components

### ISSUE THREAD

**Issue by finnlewis** [localgovdrupal/localgov_microsites#183]
### User story

As a microsite editor
I want to create layouts and paragraph components in my event
So that I can make the event attractive to our target audiences

### Notes: 

Can we create this field in the https://github.com/localgovdrupal/localgov_paragraphs/tree/2.x/modules/localgov_paragraphs_layout module?

This will be optional but will bubble up to LocalGov Drupal and to LocalGov Microsites.

**Comment by msayoung** [comment]
Started here: https://github.com/localgovdrupal/localgov_microsites_group/pull/161 

We just need to programmatically create the field groups we need, and put the relevant fields in it. Leaving with Mark to complete.
