### ISSUE TITLE
Microsite controller: manage users on microsites

### ISSUE THREAD

**Issue by finnlewis** [localgovdrupal/localgov_microsites#19]
## User story

As a Microsite Conrtoller

I want to create a new user A and grant user A ownership of site X 

I want to create a new user B and grant user B ownership of site Y

So that: 

We can add users to the site to assign roles.

Notes: 

Assume this is creating a user on the entire system, then add to the sites.

## Acceptance tests

1. Create 'user A'
2. Add user a to 'site X'
3. Create 'user B'
4. Add 'user B' to 'site Y'
5. Log in as 'user A'
6. Be able to edit config on 'site X'
7. **Not** edit the config on 'site Y'
8. Log in as 'user B'
9. be able to edit config on 'site Y
10. **Not** edit the config on 'site X'

**Comment by ekes** [comment]
Potential assumption implicit, or following from the implementation of, the above:-

The microsite administrator can't add users to the microsite. They can set, and change, the permissions of the users assigned to their microsite but can't actually add users themselves?

Present implementation makes it possible to add users on the main site; and add users to microsite groups on the main site (so a microsite administrator could do this there if they were permitted to log into the main site); but on the microsite itself _only_ those users in the microsite group are visible. This is not set in stone, just the current working arrangement.

**Comment by finnlewis** [comment]
Write up discussion from sprint review.

**Comment by finnlewis** [comment]
Potential dupe?

**Comment by finnlewis** [comment]
I think is done, tested creating two sites with two users, and the permissions work as expected. 

As you mention @ekes - the ability for a 'microsite admin' to create new users on the system might well be something we need to explore at some point. I'll add a new issue for that.

**Comment by ekes** [comment]
As promised at the time there already is an issue https://github.com/localgovdrupal/localgov_microsites/issues/92 with my first research on it.
