### ISSUE TITLE
Extend responsive preview permissions

### ISSUE THREAD

**Issue by msayoung** [localgovdrupal/localgov_microsites#191]
Ensure microsite editors and admins have permission to preview
Extend to content types beyond the page

**Comment by finnlewis** [comment]
? related to https://github.com/localgovdrupal/localgov_microsites/issues/190

**Comment by msayoung** [comment]
@finnlewis do you remember testing this from within a microsite? it's not working now, if it ever did :( 

It works when you add content _not_ within a group.

**Comment by finnlewis** [comment]
I think I recall testing it within a microsite.... but I'm not 100%. I will test.

**Comment by msayoung** [comment]
It seems that Microsite admins can't preview content at all, which is going to stop the responsive preview from working .

**Comment by msayoung** [comment]
Ok, a trusted content editor can preview content as long as it's been saved already. The PRs below add the ability to preview news and the permission to use responsive preview for the trusted content editor. 

- https://github.com/localgovdrupal/localgov_news/pull/68
- https://github.com/localgovdrupal/localgov_microsites_group/pull/157

**Comment by msayoung** [comment]
@finnlewis - can you confirm whether we want / expect microsite admins to be able to preview unsaved content. 
Also do we want to be able to save content as unpublished?

**Comment by finnlewis** [comment]
I think a microste admin or microsite editor would like to able to save content without publishing. 
Preview unsaved content? No idea, it's a bit hard isn't it? If so, let's just say no for now.

**Comment by msayoung** [comment]
Ok, adding another ticket in todo for saving unpublished content. otherwise the rest is merged

**Comment by willguv** [comment]
Can't they save to draft? Feels a bit odd that they can't start working up content and come back to it later

Have I misunderstood something here? :)

**Comment by msayoung** [comment]
Yes, we added save as unpublished. this was an old ticket that wasn't marked as closed, sorry for the alarm :)

**Comment by willguv** [comment]
@msayoung no worries or alarm, thought it best checking
