### ISSUE TITLE
Create 'subsite overview' page on each site

### ISSUE THREAD

**Issue by finnlewis** [localgovdrupal/localgov_microsites#20]
## User story

As a site owner.

I want to create content on my site.

So that..... duh!

## Acceptance tests

1. Log in 'user A'
2. Create a subsite overview page on 'Site X'
3. Log out and see it on sitex.lndo.site
4. Not see it on sitey.lndo.site
5. Log in 'user B'
6. Create a subsite overview page on 'Site Y'
7. Log out and see it on sitey.lndo.site
8. Not see it on sitex.lndo.site.

**Comment by ekes** [comment]
Related implementation detail (this is in the assumption log?):-

There is one microsite group type that can _all_ have _all_ the (localgov) content types that are enabled on the site. If there is only subsite overview enabled that's all that's there; but if directory is there too that can be enabled on all microsites. This as opposed to having different types of microsite groups that are defined by what sort of content can be posted in them.
Reasoning:
 * Microsite groups will later want to have more content types than when they were originally defined.
 * Permissions can restrict per microsite group (per user) so it is not that every user can see every content type in every microsite.

**Comment by willguv** [comment]
@ekes if can I try playing this back to you? Are you saying:

- a microsite will be able to use all existing LGD content types by default

- whoever sets the user permissions for that microsite will be able to restrict content types on a per user basis

If so, I think this is exactly how it should work

**Comment by willguv** [comment]
Also @finnlewis that's my favourite user story ever :)

**Comment by ekes** [comment]
>   a microsite will be able to use all existing LGD content types by default

All that are provided by modules enabled on that site yes.

>  whoever sets the user permissions for that microsite will be able to restrict content types on a per user basis

Yes.
