### ISSUE TITLE
Sprint notes for Sprint 7

### ISSUE THREAD

**Issue by msayoung** [localgovdrupal/localgov_microsites#200]
https://docs.google.com/document/d/1pwnn5khyZccgWAzuw7rO9pXeS2tHePUo_Tp9i21gjmE/edit#

**Comment by msayoung** [comment]
https://stage.agile.coop/blog/sprint-7-notes-local-gov-drupal-microsites/

**Comment by msayoung** [comment]
Putting @finnlewis 's face on this for feedback. I'd like to publish today if poss

**Comment by finnlewis** [comment]
Thanks @msayoung - noted!

**Comment by finnlewis** [comment]
Made some notes, reads well, I'm happy! 
Thanks @msayoung !
