### ISSUE TITLE
Configuration objects provided by localgov_microsites_events have unmet dependencies

### ISSUE THREAD

**Issue by finnlewis** [localgovdrupal/localgov_microsites#204]
Fresh install locally is failing with: 
            

>   Configuration objects provided by <em class="placeholder">localgov_microsites_events</em> have unmet dependencies: <em class="placeholder">field.field.node.localgov_event.lgms_banner (field.storage.node.lgms_banner)</em>

**Comment by ekes** [comment]
Fixed with https://github.com/localgovdrupal/localgov_microsites_group/pull/166 re-open if not.
