### ISSUE TITLE
Microsite administrator - can set some theme variables 

### ISSUE THREAD

**Issue by finnlewis** [localgovdrupal/localgov_microsites#21]
As a microsite administrator

I want to be able to edit some properties of the theme look and feel.

So that I can override colours or layout or fonts.

## Notes: 

Initially we just need to define the architecture for editing and storing the property vars and passing to the theme. 
Later we will have fun with forms and tabs and brilliant admin user experience.

## Acceptance tests: 

1. Log in
2. Edit some theme settings
3. Log out

**Comment by msayoung** [comment]
done as part of the project.
