### ISSUE TITLE
Remove View relation from Operations

### ISSUE THREAD

**Issue by msayoung** [localgovdrupal/localgov_microsites#216]
![Image](https://user-images.githubusercontent.com/3852805/180813217-e0a67800-e69d-4bf3-a1e5-af2d87dce15d.png)

**Comment by ekes** [comment]
Testing https://github.com/localgovdrupal/localgov_microsites_group/pull/210

**Comment by msayoung** [comment]
Theres still the missing local actions menu, but I've created a new issue for it localgovdrupal/localgov_microsites_group#261 
closing this one
