### ISSUE TITLE
Confirm categorisation of majority of microsites

### ISSUE THREAD

**Issue by finnlewis** [localgovdrupal/localgov_microsites#22]
Confirm the categories of 

- type
- audience
- feel (?)

This is in order to be able to articulate the distinct needs of each category. 

Will will use this to determine whether there are preset configuration / themes for the different categories

**Comment by finnlewis** [comment]
Richard is going to try to take this forward while Maria is off.

**Comment by richard-s-rowley** [comment]
I have been through about 40 of the sites and have refined the categorisation a little:

See https://miro.com/app/board/uXjVOStMNW8=/?moveToWidget=3458764523618545277&cot=14

1. There are three main types of site from an audience point of view.
• A specialist adult audience (advice seekers): these can look broadly like "council sites"
• Young people audience: these are normally for advice seekers but age appropriate in visual design
• Consumers (tourists, investors): these look very unlike council sites and are designed to attract people (or their money)

2. In terms of functions there are four major categories:
• Advice and info - the largest number by far
• Directory (of external resources)
• Tourist attraction  
• Advertising for a project, campaign or private service. There are typically very few calls to action from these sites.

Many sites span more than one of these categories, however.

3. The main content types are repeated, though they might work slightly differently in each of the functional categories:
- home  
- section  
- info  
- resource  
- - custom resource types  
- article  
- - news
-  - blog
- person  
- event
