### ISSUE TITLE
Allow people to crop image after upload

### ISSUE THREAD

**Issue by markconroy** [localgovdrupal/localgov_microsites#220]
This module should fix this:
https://www.drupal.org/project/media_library_edit

**Comment by markconroy** [comment]
This is going to take a significant amount of work. We need to:

- Require the module in every repo that uses media
- Edit the "Manage form display" page for each media field - image, video, file, map, etc
- Set the field formatter to include the edit button
- Export the config
- Create a PR

Is this more work than we should be taking on for microsites (before we know if we have more budget) @finnlewis @msayoung @willguv ?

**Comment by msayoung** [comment]
We should also have it on LGD main in due course. 
Lets put this in the "To Be Prioritised" column for now.

**Comment by msayoung** [comment]
The other options (rather than updating the config for every media field)  is to patch core as per https://www.drupal.org/project/drupal/issues/2985168 
The functionality will be rolled into Drupal Core eventually so that _may_ be the path of least resistance? 

@stephen-cox thoughts?

**Comment by markconroy** [comment]
@msayoung That sounds like a better plan, though that issue is currently marked as "postponed" until they have feedback from the UX and a11y teams - https://www.drupal.org/project/drupal/issues/2985168#comment-14292619

**Comment by msayoung** [comment]
Enabled in localgov_core: https://github.com/localgovdrupal/localgov_core/pull/146
Added to localgov_paragraphs: https://github.com/localgovdrupal/localgov_paragraphs/pull/82

**Comment by msayoung** [comment]
Lets see if they make it through, and then we'll add to events and news

**Comment by finnlewis** [comment]
Still needs testing!
