### ISSUE TITLE
Permission to save unpublished content (trusted editor)

### ISSUE THREAD

**Issue by msayoung** [localgovdrupal/localgov_microsites#221]

**Comment by stephen-cox** [comment]
Unfortunately. this isn't as simple as just assigning the right permissions. There look to be fundamental issue with creating unpublished content in a group. User 1 can't do it and the Group issue queue is full of queries about this.

Allowing users to create unpublished content is going to need further looking into.

**Comment by stephen-cox** [comment]
Turns out this only effects LocalGov Pages and not just group pages; all page edit forms are missing the publish checkbox.

It doesn't look to be a config option. Inspecting the form array, status key is there, but is mostly missing most of the settings. I'm yet to find how it is happening.
