### ISSUE TITLE
Confirm the content types available for MVP

### ISSUE THREAD

**Issue by msayoung** [localgovdrupal/localgov_microsites#23]
## Notes: 

Maria will make a proposal as to the content types we want to ship as MVP.
We might exclude the 'services' content types.
We might include a new content type such as 'standard page'

To be proposed, reviewed, discussed, decided!

**Comment by finnlewis** [comment]
Richard is going to try to take this forward while Maria is off.

**Comment by msayoung** [comment]
Made good progress on this in the working group meeting. 

- [Wireframes](https://miro.com/app/board/uXjVO9o1iRk=/?moveToWidget=3458764523794796901&cot=14)
- [Slidedeck](https://docs.google.com/presentation/d/1qTt4sxv2EJFsC9Xi3V3Uahfr_wZBtsBJ-qO9Ydj4GWo/edit#slide=id.g1222f811dd7_0_798)
