### ISSUE TITLE
Bug: as a microsite admin I can see other ste's dashboard and do things

### ISSUE THREAD

**Issue by msayoung** [localgovdrupal/localgov_microsites#231]
If I log in to https://site4.bathnes.localgovdrupal.org/ as the microsite admin of that site I can go to https://site4.bathnes.localgovdrupal.org/group/5/domain-settings

**Comment by ekes** [comment]
Just to check this is only the group domain settings: /group/{group}/domain-settings not any other /group/{group}/path?

**Comment by ekes** [comment]
Also which tabs for settings can you see?
It is the tab that should give access to the page - unless you user has 'bypass domain group permissions' permission.

**Comment by ekes** [comment]
Also note from manual testing:-

Where group/1 is localgov-micro-1.lndo.site and group/2 is localgov-micro-2.lndo.site

Admin of group/1 can log into localgov-micro-1 and 2 -- this is expected, there was an issue about doing some redirect magic somewhere... but no really satisfactory solution.
Admin of group/1 can see group/1/domain-settings on localgov-micro-1 and unfortunately but not seriously localgov-micro-2 -- I think this can be fixed as they can't see /group/1 on localgov-micro-2 just localgov-micro-1, so we can add that permission as an 'and'
Not serious as they cannot see group/2/domain-settings on either localgov-micro-1 or 2.

**Comment by msayoung** [comment]
Ok, false alarm. I had microsite admin role on both sites. 
closing this. 

sorry and thanks @ekes
