### ISSUE TITLE
Multiple teasers block: display inline or not

### ISSUE THREAD

**Issue by msayoung** [localgovdrupal/localgov_microsites#234]
The expectation seemed to be that multiple teasers added through the Teasers paragraph would appear in a row.

**Comment by msayoung** [comment]
@markconroy - do you have thoughts on this one?

The Teasers block allows for a Heading and multiple teaser blocks. These currently appear in a single column, rather than in a row. 

Given that they _could_ be put in a full-width column or 1/3 column what's the best approach?

Should we give the option for column (at wider screens) or row on the Paragraph?

**Comment by markconroy** [comment]
I think the general layout of the teasers is going to mean they should be 1 per row. Not sure how you'd squash 3 of those things into a row when we have the image on left and title/etc on right (until container queries arrive in CSS).

We could give another display in each view for 'Card' and put them in a 3-in-a-row format?

**Comment by msayoung** [comment]
I think the teaser ones do have the "card" layout, don't they? 

We could also swap to the single teaser paragraph if that's clearer for folks

**Comment by markconroy** [comment]
They have the 'teaser' view mode. Even the cards at the top of the newroom use a version of that, rather than a card view mode. I created an issue last year for us to add a card view mode to LGD but it hasn't gotten much traction

**Comment by msayoung** [comment]
@markconroy - what do you think about removing the **Featured teasers** paragraph from those offered, and replacing with the **Featured teaser** paragraph?

My hunch is that this will be clearer for people.

**Comment by markconroy** [comment]
I'm not sure it would make much of a difference. And having the container around it makes it handy for styling when there is more than on featured teaser.

**Comment by msayoung** [comment]
Ok. Then I think we can close this.
