### ISSUE TITLE
Contact forms for each microsite

### ISSUE THREAD

**Issue by finnlewis** [localgovdrupal/localgov_microsites#235]
## User story 

**As a** microsite editor

**I want** to have a simple contact form for which I can configure the destination email

**So that** we can encourage visitors to get in touch with us. 

### Notes: 

In the microsites working group meeting this was considered a must have feature. Notes are here: https://docs.google.com/document/d/1Y63d87PP6gc89m01NjJRUwsLzv5GWxRxDXgRG3-vbM4/edit#heading=h.lmjuqvwm89xn

The current understanding is that webform will not work with group module 1.x, as we can't easily assign config entities to a group. group 2.x / 3.x might allow us to pursue this path. 

In the mean time it is worth exploring the Drupal core contact form module. Does it play nice?

**Comment by stephen-cox** [comment]
The core contact forms are also config entities so, like Webform, there's no easy way to make these into Group managed content.

If we're only going to have a few of these, we could look at giving Microsite Controllers the ability to create them and assign them to a site, but I can't see any easy way to allow site admins and editors to create them.

**Comment by msayoung** [comment]
Angie sent over these as examples, with the message:

_Here are screenshots of to of two contact forms currently used. The fostering form was created by an external org and has basic branching._

[Croydon Safeguarding Children Partnership.pdf](https://github.com/localgovdrupal/localgov_microsites/files/9555616/Croydon.Safeguarding.Children.Partnership.pdf)
[Fostering Enquiry Contact Form1.pdf](https://github.com/localgovdrupal/localgov_microsites/files/9555620/Fostering.Enquiry.Contact.Form1.pdf)
[Fostering Enquiry Contact Form2.pdf](https://github.com/localgovdrupal/localgov_microsites/files/9555621/Fostering.Enquiry.Contact.Form2.pdf)
[Fostering Enquiry Contact Form3.pdf](https://github.com/localgovdrupal/localgov_microsites/files/9555618/Fostering.Enquiry.Contact.Form3.pdf)
[Fostering Enquiry Contact Form4.pdf](https://github.com/localgovdrupal/localgov_microsites/files/9555619/Fostering.Enquiry.Contact.Form4.pdf)
[Fostering Enquiry Contact Form5.pdf](https://github.com/localgovdrupal/localgov_microsites/files/9555615/Fostering.Enquiry.Contact.Form5.pdf)
[Fostering Enquiry Contact Form6.pdf](https://github.com/localgovdrupal/localgov_microsites/files/9555617/Fostering.Enquiry.Contact.Form6.pdf)

**Comment by finnlewis** [comment]
I think we need to create a solution for this. 

@ekes and @stephen-cox were discussing embedding a webform in a node and passing config from the node fields to the embedded webform to override certain fields / config values. 

Is this a goer?

**Comment by finnlewis** [comment]
@stephen-cox perhaps we discuss the feasibility of Group 3.x with @ekes first, at which point Drupal core contact forms should be easier.

If we're not going the Group 3.x route, we look at the "embedding a webform in a node and passing config" route. 

If we are going the Group 3.x route... we might have more flexibility.

**Comment by finnlewis** [comment]
> embedding a webform in a node and passing config from the node fields to the embedded webform to override certain fields / config values.

@ekes has done this in the past.

If we can get away with: 

 - one webform
 - simple config override
 - ability to reference from the group entity (one contact form per group / microsite)

Then maybe this will be quick!

**Comment by willguv** [comment]
@finnlewis @ekes I think this a good workaround, thanks. We should mention this along with a move to group 3.x when available which will open up the possibility of integrating with Croydon's Webforms work

**Comment by finnlewis** [comment]
@ekes has made a start on this. 

Scenario 1: 

- Controller makes a contact form on the control site. 
- Site admins can enable this on a site by site basis. 
- This results in a consistent in layout and form fields.
- Will need to override the email address for each 

Scenario 2: 

- Allow a microsite admin to create a custom webform for their site. 
- This is possible, but currently feels like more work.

Scenario 1 does not rule out extending to scenario 2.

**Comment by ekes** [comment]
Super basic foundation for Scenario 1 https://github.com/localgovdrupal/group_webform
I'm unsure if it should be a generic module, with a localgov_microsites_webform submodule tweaking it, or if we should just go in and customize for our specific use case in a module that declares the group relatioship type.

Presently the code is based on gnode, it's kinda the basic you need to make a relationship to entity type in a group. Everything ends up with the default group content urls and admin lists. So they probably want tweaking.

Permission options are too. Turning on and off individual webforms would then be a group_permissions task -- like turning off content types: events, news etc.

For mailing forms etc. it should be possible to use tokens. The site admin email for example is different per domain, so a token for that value would send it to the domains email address. Tokens can also be used to get values from where webforms are embedded, depending how this is done.

**Comment by finnlewis** [comment]
@finnlewis to test this!

**Comment by finnlewis** [comment]
My testing is looking promising, but I need to work out the list of tasks to make this operational.

Currently I have done the following: 

1. Cloned the https://github.com/localgovdrupal/group_webform module and enable it
2. Enable the plugin at https://localgov-micro.lndo.site/admin/group/types/manage/microsite/content (Group webform (Contact)).
3. Set permissions at https://localgov-micro.lndo.site/admin/group/types/manage/microsite/permissions set admin permissions to grant : 

Entity: Add submission entities
Entity: Delete any submission entities
Entity: Delete own submission entities 
Entity: Edit any submission entities 
Entity: Edit own submission entities
Entity: View any submission entities

5. Find the url of the contact from from https://localgov-micro-1.lndo.site/group/1/content/create (listing all entities that we can creat)
6. As anonymous, go to https://localgov-micro-1.lndo.site/group/1/content/create/group_webform%3Acontact 
7. See webform and make a submission
8. As anonymous, go to https://localgov-micro-2.lndo.site/group/1/content/create/group_webform%3Acontact
9. As admin 1 on site 1 visit https://localgov-micro-1.lndo.site/admin/structure/webform/manage/contact/submission/1 and see the sumbission
10. As admin 2 on site 2 visit https://localgov-micro-2.lndo.site/admin/structure/webform/manage/contact/submission/1 and see access denied (so group permissions work!)
11. As anon visit both of the above and see access denied.

**Comment by finnlewis** [comment]
Next up, need an itemised list of tasks to make this usable. 

1. Allow the webform to be embedded in a paragraph. 
2. Provide a way for the site admin to override the target email address for submissions to be sent to.
3. Provide a listing of webform submissions on the microsite

**Comment by msayoung** [comment]
## Notes



- [ ] - Do we want a default Url alias
- [ ] - this message is displayed to the microsite admin, they dont have access to the link:

![Image](https://user-images.githubusercontent.com/3852805/204538009-41a775e5-5fe0-40ce-b6b7-c1089fbc3f87.png)


- [x] - error messages displayed inline ( require inline-form-errors ) , disable client-side validation
- [x] - required field indication 
- [x] - require the confirmation message 


## Styling

- [x] - confirmation message needs styling
- [x] - required field indication 


## Access.
2 microsites each with one webform each

/node/5 belongs to microsite 2
http://localgov-micro-1.lndo.site/node/5/webform/results/submissions - can access this page though there are no submissions

**Comment by msayoung** [comment]
we also need to enable the localgov_microsites_group_webform module in the profile

**Comment by msayoung** [comment]
and finally, do we want microsite controllers to be able to create webforms ? currently they can't

**Comment by msayoung** [comment]
I've added a couple of things here: https://github.com/localgovdrupal/localgov_microsites_group/pull/347 for your review @finnlewis

**Comment by msayoung** [comment]
Styling changes here: https://github.com/localgovdrupal/localgov_microsites_base/pull/180

**Comment by finnlewis** [comment]
We've merged this in now, good work all!
