### ISSUE TITLE
Site administration menu: streamline / simplify

### ISSUE THREAD

**Issue by msayoung** [localgovdrupal/localgov_microsites#236]
Feedback from user testing found the proliferation of admin menus took up valuable screen space. Also the difference in appeareance of the Microsite Local tasks was confusing (in the different themes). 

I've done a little  research and wonder if the following would be better

The toolbar_menu module allows you to place a menu as an item in the toolbar, and limit (by Drupal role) who has access to it. I've added one called "Microsite Admin" in the screenshot below.

I've used the Tools menu, but we would need to create a menu which could be referenced by this - I assume this is possible? 

![Image](https://user-images.githubusercontent.com/3852805/188665329-05735e1b-0b88-4de2-8784-642d9f4e8688.png)

If we went with this we could remove the microsite local task menu from the frontend at least. 

We can also enable Local Tasks in Admin Toolbar Tools (which we're also using) which adds the local tasks to the toolbar. See the right of the screenshot above. This current shows Edit / View etc on the frontend, and all the microsite admin when in the admin theme.

@stephen-cox - you had thoughts concerns about this. What do you think? 
@willguv @markconroy @finnlewis thoughts?

**Comment by stephen-cox** [comment]
If I understand the first issue correctly, the local tasks for managing a site and the menu bar are taking up too much space.

It seems to me we either remove the menu from site admin and editors or move the local tasks into the menu. The local tasks option in the menu seems to hide this away and it's clear that you would find these functions behind a link called 'Local Tasks'. We could rename this to make it clearer, but it's still hidden away. I'm not sure it's easy to create a menu of local tasks like these as they are specific to the site we're on and so require group context.

Personally, I think the menu bar is redundant for site admins and editors. It's only needed for the responsive preview, which I think is a nice to have and so could be lost if there's no way to move the toggle button out of the menu.

The second issue, the local tasks for site management not being distinct enough, can be solved with some theming to differentiate them from the node edit local tasks.

@msayoung Does this address the issues raised or have I missed anything? Was there any feedback from users on the responsive preview?

**Comment by msayoung** [comment]
thanks @stephen-cox 

The only feedback on the responsive preview was from Will , later , that he hadn't noticed it. It is a useful function though, so it would be good to keep it if we can.

Without the responsive_preview I think the menu bar is redundant, unless we move the microsite tasks to it, which we can do with something like toolbar_menu - but as you say, may be difficult. 

We could theme the microsites tasks to look more distinct, and maybe take up less space. 

I wonder if @willguv has any thoughts?
Lets discuss in Sprint Review / Planning.

**Comment by finnlewis** [comment]
From discussion: 

If we can create a link in the admin menu to the dashboard (/group/[grou_id]
We can then hide the group menu from content pages / front end pages
All links to group menu can then only be accessed from the dashboard. 

@stephen-cox is this possible?

@markconroy wonders if Shortcut module might help?

**Comment by willguv** [comment]
@msayoung let's briefly consider the ordering of menu items when we do this work, and add an extra card if needed

**Comment by stephen-cox** [comment]
I have a proposed solution to this.

PR https://github.com/localgovdrupal/localgov_microsites_group/pull/260 creates a menu link that is only displayed when on a microsite. Clicking on the link redirects to the current group.

How does this sound? Happy to demo it if it's unclear

**Comment by markconroy** [comment]
Sounds good.
