### ISSUE TITLE
Allow a non-cropped image to be uploaded through the WYSIWYG

### ISSUE THREAD

**Issue by msayoung** [localgovdrupal/localgov_microsites#239]
Trying to add the site logo to the footer. can't get an uncropped version

![Image](https://user-images.githubusercontent.com/3852805/187495722-5850071a-1cf4-476e-8219-d7882660a941.png)

**Comment by msayoung** [comment]
In order to do this I propose that we

1. Create a new crop type called "Freestyle" with no aspect ratio set
2. Create a new image style using this crop type
3. Enable this on the Image Media Type Form Display
4. Create a new display mode for the Image Media Type
5. On the display for the Image set the image field to use the Freestyle image style
6. Allow the Freestyle display mode on the Ckeditor settings

Questions - 

1. would it be better to just show the original image without a crop?
2. should there be a responsive image style in the mix?

**Comment by finnlewis** [comment]
It would be good to have decent cropping set up. 

So I think: 

1. no
2. yes

**Comment by finnlewis** [comment]
Note: presumably this will be added to localgov drupal media rather than microsites specifically.

**Comment by msayoung** [comment]
I think we have some clever override for our microsite's WSYWYG actually, so while it's available in LGD Core the WYSWYG won't update automatically 

https://github.com/localgovdrupal/localgov_core/pull/145
https://github.com/localgovdrupal/localgov_microsites/pull/262

**Comment by msayoung** [comment]
It sounds like there is a request for this in the wild, so we should get it in to core too
