### ISSUE TITLE
demo.microsites.localgovdrupal.org and demo content

### ISSUE THREAD

**Issue by msayoung** [localgovdrupal/localgov_microsites#245]
Discussing this in sprint planning.

The user need for this is to be able to demonstrate the microsites functionality rather than give devs the ability to install lots of default content on their local.

There are complexities using default content (as used in the localgov_demo module) but we might want to look at this later. 

## User story

As LocalGov Comms
I want a demo site 
So that we can show off the functionality.

Solution: 

Set up 

demo.microsites.localgovdrupal.org (control site)
site1.demo.microsites.localgovdrupal.org 
site2.demo.microsites.localgovdrupal.org 
site3.demo.microsites.localgovdrupal.org 

Invite comms and people to a microsites content hackathon!

Taks: 

- [x] Set up demo sites with known domains. 
- [x] Set up meetings / workshop
- [x] Spend some time populating a number of sites.
- [x] Wrap up the sites as a database dump and files dump
- [ ] Set up automation to re-install every day.
- [ ] Document the sites and users and details.

**Comment by finnlewis** [comment]
@stephen-cox will email DNS people and copy in @willguv

**Comment by finnlewis** [comment]
We've scheduled a meeting Wes 19th 2pm - 4pm to get started with content, assuming the DNS and sites are in place.

**Comment by stephen-cox** [comment]
Site are up and running:

  - https://demo.microsites.localgovdrupal.org/
  - https://site1.demo.microsites.localgovdrupal.org/
  - https://site2.demo.microsites.localgovdrupal.org/
  - https://site3.demo.microsites.localgovdrupal.org/

Will post user details in Slack

**Comment by finnlewis** [comment]
Ready for content, Maria and I will liaise to arrange a workshop

**Comment by msayoung** [comment]
Current thinking is to recreate 3 sites - 1 of each of the types defined early on:

- advice, resources or a directory  
- attraction/destinations
- commercial services

I think we should try to find a good site to copy, but remove any references to a real place with Scarfolk, as we did on the original demo site. 

## Advice, resources, directory site

Council look and feel
Directory of information , News, Events

https://livingindependently.lbhf.gov.uk/

- All our litmus sites are about child protection etc, which I dont think is exactly the right example for us. I'll look for another

## Attraction / destination

Bespoke / modern look and feel. 
I suggest we use something like the William Morris gallery, with design inspired by Birkenhead Park. https://birkenhead-park.org.uk/ or Roman Baths: https://www.romanbaths.co.uk/

Events, fancy landing pages

## Commercial services

Some kind of venue / wedding site ?
https://sixtybricks.co.uk/

## Blog

Council feel 
https://digital-blog.blackburn.gov.uk/

**Comment by msayoung** [comment]
Deployment notes

I've just taken a backup of the demo site to test the update process. 

- uninstall lgd_claro before running updates
- import config for https://github.com/localgovdrupal/localgov_microsites_group/blob/1.x/modules/localgov_microsites_events/config/optional/views.view.lgms_embed_view_events.yml  ( need to add the UUID) - this should fix the errors on site 3 homepage.

**Comment by finnlewis** [comment]
@msayoung and @willguv discussed creating a site4 that just has blogs on it.
