### ISSUE TITLE
Release plan for LocalgGov Microsites - Alpha / Beta / Stable

### ISSUE THREAD

**Issue by finnlewis** [localgovdrupal/localgov_microsites#251]
- [ ] Roadmap for alpha / beta / stable releases and 1.x / 2.x
- [ ] Date for alpha release ( may be breaking changes)
- [ ] Date for beta (expect no breaking changes)
- [ ] Stable (maybe after upgrading to Group 3.x)

2.x might be ready before 1.x is stable !

**Comment by finnlewis** [comment]
We're about to start sprint 12 on Wednesday 12th October, which is the last sprint in the current schedule, but we have decided to do the work needed to upgrade to Group 3.x before we release a beta, to avoid potentially huge amounts of techincal debt for the project and for councils that make use of LocalGov Drupal Microsites. 

So, we could tag the Alpha release at the end of sprint 12 to encourage people to start testing the functionality but be clear that there will be breaking changes before a Beta release.  

Sprint 13 and 14 should then take us to a Beta release on Group 3.x. 

This would give us dates as follows: 

- Alpha 1 release: Wednesday 26th October 2022
- Beta 1 release: Wednesday 23rd November 2022
- 1.0 stable release: Wednesday 21st December 2022 (4 weeks after Beta?)

What do you think @ekes @stephen-cox @msayoung @markconroy ?

**Comment by markconroy** [comment]
Looks perfect.

**Comment by finnlewis** [comment]
@ekes mentions that the group_permissions module is a variable that we rely on. 

@stephen-cox asks about production sites during Beta. And be explicit that we are not expecting an upgrade path between Alpha and Beta.

**Comment by finnlewis** [comment]
Share this with Tim for the newsletter.

**Comment by finnlewis** [comment]
@stephen-cox suggests creating separate meta issues for a release of each alpha / beta / stable.

**Comment by finnlewis** [comment]
Update on release plan:

- Beta 1 release: Wednesday 7th December 2022
- 1.0 stable release: Wednesday 21st December 2022 (4 weeks after Beta?)

Questions on what we mean by stable release: 
 - For example, Group Permissions is doing well and tagging releases. 
 - Other modules like Group Term are still working off dev branches and forks.

- [ ] Define what we mean by 'Beta' and 'Stable' and be clear on release notes.
