### ISSUE TITLE
Sprint 11 Notes - write and publish

### ISSUE THREAD

**Issue by finnlewis** [localgovdrupal/localgov_microsites#279]
Sprint 11 is complete, so we need to write up the progress in a Sprint 11 notes blog post.

**Comment by finnlewis** [comment]
https://stage.agile.coop/blog/sprint-11-notes-local-gov-drupal-microsites/

**Comment by finnlewis** [comment]
nearly there @msayoung ?

**Comment by msayoung** [comment]
yep - go for it
