### ISSUE TITLE
Attachment component

### ISSUE THREAD

**Issue by finnlewis** [localgovdrupal/localgov_microsites#281]
Add the current Attachment paragraph type to all the paragraph fields.

**Comment by msayoung** [comment]
- [x] Page: https://github.com/localgovdrupal/localgov_page/pull/49
- [x] Events https://github.com/localgovdrupal/localgov_microsites_group/pull/279
- [x] News https://github.com/localgovdrupal/localgov_microsites_group/pull/279
- [x] Blog https://github.com/localgovdrupal/localgov_microsites_group/pull/279
- Directory Promo page not needed, as it has an attachment field already
