### ISSUE TITLE
Decide on whether to use Claro or Gin as our default admin theme

### ISSUE THREAD

**Issue by markconroy** [localgovdrupal/localgov_microsites#286]

**Comment by finnlewis** [comment]
We can now chose as a microsite admin.

- [ ] Which are we defaulting to for screenshots etc? 
- [ ] What do the microsites working group? 

Will: thinks Claro, more accesible. 
Maria: Claro, more accesible.
Ekes: don't care
Stephen: Claro menu handling annoys the hell out of me! , so Gin
Finn: Gin. Feels nicer.
Mark: Claro, use core as much as possible, better test coverage

**Comment by willguv** [comment]
@msayoung what did you decide? Claro as default, make it easy to switch?

**Comment by markconroy** [comment]
Yes,  Claro as default and you can set an admin theme per microsite via the Site Settings page.
