### ISSUE TITLE
Drupal architecture - investigate Group contrib ecosystem

### ISSUE THREAD

**Issue by msayoung** [localgovdrupal/localgov_microsites#3]

**Comment by finnlewis** [comment]
@ekes has started looking at https://www.drupal.org/project/domain_group with https://www.drupal.org/project/group and https://www.drupal.org/project/domain

**Comment by finnlewis** [comment]
See notes here: https://docs.google.com/document/d/1C3evW6nb_PCT4mKi4PHWt5bPXNiRo-YiTTT5VOmkqvw/edit
