### ISSUE TITLE
Domain Group upgrade

### ISSUE THREAD

**Issue by ekes** [localgovdrupal/localgov_microsites#300]
This ties domain to group. 

It provides the access control to say this content entity is in this group. Anything that can go into a group can also go into a domain. It extends the entity access query to check the domain and enforce the group. So if you are trying to access a content entity on the wrong domain, you will not be able to see it.

@ekes forked this here: https://www.drupal.org/sandbox/ekes/3278349 
We are using the sandbox version at the moment. 
This took @ekes a couple of weeks to write, so: 
  - he knows how it works
  - it should be quicker to update. 

Estimated dev time: 1 dev 1 sprint

**Comment by ekes** [comment]
Largely done:
 * Needs further manual testing
 * Wants an issue to make an official branch

**Comment by finnlewis** [comment]
Steps to test [domain](https://www.drupal.org/project/domain_group)

1. Vanilla install of Drupal 9 (in our microsites container)
2. Group 3.x
3. Install sandbox https://www.drupal.org/sandbox/ekes/3278349

Note, this has no glue code, so to test: 

- Create two domains
- Create two groups 
- Post content into each group
- Confirm that content is available in each group.

**Comment by ekes** [comment]
For work on making a non-sandbox version:-
https://www.drupal.org/project/domain_group/issues/3319678#comment-14776257

**Comment by finnlewis** [comment]
I've been testing this and it does seem to be working well!
