### ISSUE TITLE
Group content menu upgrade

### ISSUE THREAD

**Issue by ekes** [localgovdrupal/localgov_microsites#302]
@ekes suggests looking at gnode and ginvite for a lead on how to upgrade this to 3.x 

Once we've reviewed ginvite, this should be quicker. 

Estimated dev time: 1 dev 1 day 

Only looks to be a 1.x branch. Might be easier in Group 3.x as config entities are supported.

**Comment by ekes** [comment]
Working branch https://www.drupal.org/project/group_content_menu/issues/3315163 with broken permissions.

**Comment by finnlewis** [comment]
Tasks: 

- [x] Get the permissions right!
- [ ] Write patches or work arounds for our use cases if needed.

**Comment by ekes** [comment]
Permissions are fixed. I've now made a request to make a branch of this. We'll see how it progresses.

**Comment by finnlewis** [comment]
Testing locally seems good to me.

We need to chase the maintainer to make a branch / release.
