### ISSUE TITLE
Group term upgrade

### ISSUE THREAD

**Issue by ekes** [localgovdrupal/localgov_microsites#303]
@ekes suggests looking at gnode for a lead on how to upgrade this to 3.x 

This could be just search and replace on methods and names. 

Estimated dev time: 1 dev 1 day

**Comment by finnlewis** [comment]
Someone has made a start: https://www.drupal.org/project/group_term/issues/3316529

**Comment by ekes** [comment]
Branch made - can't make one on do. at the moment I think there's 'issues' with gitlab integration. Patch applies, but it's going to need Tests.

**Comment by ekes** [comment]
OK in _failing_ to write the tests I found all the issues with the module I think, and have pretty much followed gnode. The only test that would make sense is some integration test I think.

Added the sandbox fork (as issue forks are broken) to the composer.json https://github.com/localgovdrupal/localgov_microsites_project/commit/a97d68b99044561e196f258b7078c48db288ac4b and https://github.com/localgovdrupal/localgov_microsites_group/commit/ecf5bda7f8f8588286fd4b542cdbf07bc620afc5

**Comment by finnlewis** [comment]
This now installs, but will need testing.

**Comment by finnlewis** [comment]
Branch and request on d.o

Need to chase mainainters

**Comment by finnlewis** [comment]
Closing this as it works, but would like to get the module updated on Drupal.org
