### ISSUE TITLE
Group permissions upgrade

### ISSUE THREAD

**Issue by ekes** [localgovdrupal/localgov_microsites#304]
### https://www.drupal.org/project/group_permissions

No idea! Let's ask [LOBsteRR](https://www.drupal.org/u/lobsterr). 

See: https://www.drupal.org/project/group_permissions/issues/3308272

Sounds like it is in hand and will be worked on soon! 

Also see https://www.drupal.org/project/group/releases/3.0.0-beta1 

Estimated dev time: ???? none if LOBsteRR does it.... but there doesn't appear to be a huge amount of code.

**Comment by finnlewis** [comment]
Tasks: 

- [x] Check with maintainer how they are getting on.
- [x] Decide whether to wait for upgrade or write a workaround

**Comment by finnlewis** [comment]
This is kind of done, but we need to review / test / fix our integration

**Comment by finnlewis** [comment]
Our integration uses this to enable / disable content types.

- [x] test this thoroughly
- [x] fix any issues

**Comment by finnlewis** [comment]
This is done, we are now seeking a new release from the maintainer.
