### ISSUE TITLE
Plan user testing

### ISSUE THREAD

**Issue by msayoung** [localgovdrupal/localgov_microsites#31]

**Comment by msayoung** [comment]
Some thinking began here: https://miro.com/app/board/uXjVOStMNW8=/?moveToWidget=3458764524020235008&cot=14

**Comment by finnlewis** [comment]
We also have the notes from a meeting that @richard-s-rowley and I had: 
https://docs.google.com/document/d/1oneBqjxeLE5zIOtLZQztJeVJa8bA7or4R8rjAcsCh0I/edit

@richard-s-rowley could we list out what other tasks need to be done to consider this done?

**Comment by finnlewis** [comment]
This should be covered by 

- #62 
- #63 
- #64

**Comment by finnlewis** [comment]
We can close this one, it is covered by the other issues above.
