### ISSUE TITLE
accessibility: Search blocks have duplicate IDs

### ISSUE THREAD

**Issue by finnlewis** [localgovdrupal/localgov_microsites#311]
Found duplicate ID. Duplicate ID errors are known to cause problems for assistive technologies when they are trying to interact with content.
Please remove or change the following ID: views-exposed-form-localgov-sitewide-search-sitewide-search-page-block

**Comment by finnlewis** [comment]
@msayoung will check how this was resolved last time. Maybe hook into the block display and alter the ID based on region?

**Comment by finnlewis** [comment]
@stephen-cox in  the past has hooked into the form and generated a different ID for the form. 

hook_form_alter() .... something ?

**Comment by msayoung** [comment]
Possible one of these patches might work: https://www.drupal.org/project/drupal/issues/2968207

**Comment by msayoung** [comment]
https://github.com/localgovdrupal/localgov_microsites/pull/323
