### ISSUE TITLE
Demo sites to re-install every 24 hours.

### ISSUE THREAD

**Issue by finnlewis** [localgovdrupal/localgov_microsites#326]
@msayoung reminded us we want to reinstall the demo site every 24 hours.

@stephen-cox thinks this is quite quick - maybe an hour's work.

Once the sites are in a good state, we can take a database dump and set up the Jenkins job to reinstall every night.

**Comment by msayoung** [comment]
While we're at it can we also ensure that search engines cannot crawl these sites please?

**Comment by stephen-cox** [comment]
Everything's setup to reset the demo sites, just need to enable it.

This PR will prevent the overwriting of .htaccess and robots.txt files on core updates https://github.com/localgovdrupal/localgov_microsites_project/pull/12

**Comment by stephen-cox** [comment]
This looks to be working fine. Closing
