### ISSUE TITLE
Drupal 10 support

### ISSUE THREAD

**Issue by stephen-cox** [localgovdrupal/localgov_microsites#347]
Issue to track any changes needed to support Drupal 10

**Comment by stephen-cox** [comment]
Tasks needed for a Drupal 10 alpha release of LocalGov Microsites:

- [x] 3.x branches for Microsites profile
- [x] 3.x branches for Microsites project#
- [x] D10 support for Group Webform
- [x] D10 support for LocalGov Blogs
- [x] D10 support for LocalGov Claro
- [x] D10 support for LocalGov Forms
- [x] D10 support for LocalGov Page
- [x] D10 support for Microsites Base
- [x] D10 support for Microsites Group
- [x] All tests passing :crossed_fingers:

**Comment by stephen-cox** [comment]
PRs for D10 support

- https://github.com/localgovdrupal/group_webform/pull/7
- https://github.com/localgovdrupal/localgov_blogs/pull/20
- https://github.com/localgovdrupal/localgov_claro/pull/14
- https://github.com/localgovdrupal/localgov_forms/pull/43
- https://github.com/localgovdrupal/localgov_page/pull/52
- https://github.com/localgovdrupal/localgov_microsites_base/pull/229
- https://github.com/localgovdrupal/localgov_microsites_group/pull/414

**Comment by stephen-cox** [comment]
The version 3 of microsites installs with:

```bash
composer create-project --stability dev localgovdrupal/localgov_microsites_project MY_PROJECT
```

Next steps are to ensure Drupal installs, update the Github workflows to run the tests against D10 and fix any borked tests.

**Comment by finnlewis** [comment]
Nice one @stephen-cox 

Do you think we're ready to do an alpha release of the 3.x branch of localgov_microsites_project to encourage testing?

**Comment by finnlewis** [comment]
> Nice one @stephen-cox
> 
> Do you think we're ready to do an alpha release of the 3.x branch of localgov_microsites_project to encourage testing?

Doh, just read the comments above... sorry! Testing things now :)

**Comment by finnlewis** [comment]
@stephen-cox trying to get the Drupal site-install working for localgov_microsites. Have you managed it yet? 

After deleting a number of permissions from various install config files and some from the calls to hook_localgov_microsites_roles_default(), I've now got the following: 
                                                                                              

>   The "node_type" plugin does not exist. Valid plugin IDs for Drupal\Core\Condition\ConditionManager are: domain, group_type, current_theme, request_path, user_role, webform, entity_bundle:block_content, entity_bundle:crop, entity_bundle:geo_entity, ent  
>   ity_bundle:group_relationship, entity_bundle:group, entity_bundle:group_config_wrapper, entity_bundle:group_content_menu, entity_bundle:localgov_directories_facets, entity_bundle:media, entity_bundle:menu_link_content, entity_bundle:node, entity_bundl  
>   e:taxonomy_term, entity_bundle:webform_submission, entity_bundle:paragraph                                                                                                                                                                       

Any ideas?

**Comment by stephen-cox** [comment]
> Any ideas?

Yep - plugin id for our block visibility settings needed updating: https://drupal.stackexchange.com/questions/316150/drupal-component-plugin-exception-pluginnotfoundexception-the-node-type-plugi

**Comment by stephen-cox** [comment]
An update on what's left to do for the Drupal 10 alpha release:

Fix tests on:
- Localgov Microsites Group (https://github.com/localgovdrupal/localgov_microsites_group/pull/420/checks)
- Localgov Forms (https://github.com/localgovdrupal/localgov_forms/pull/43/checks)

Releases for:
- Group Webform (https://github.com/localgovdrupal/group_webform/pull/8)
- LGD Blogs (https://github.com/localgovdrupal/localgov_blogs/pull/22)
- LGD Claro (https://github.com/localgovdrupal/localgov_claro/pull/15)
- LGD Page (https://github.com/localgovdrupal/localgov_page/pull/53)
- Microsite Base theme
- Microsites Group (https://github.com/localgovdrupal/localgov_microsites_group/pull/420)

There are 2 PRs for the final releases once the above it done:
- https://github.com/localgovdrupal/localgov_microsites/pull/401
- https://github.com/localgovdrupal/localgov_microsites_project/pull/31

**Comment by stephen-cox** [comment]
Latest update on Drupal 10 support:

There are now 2 PRs ready for review adding Drupal 10 support to Microsites Group (https://github.com/localgovdrupal/localgov_microsites_group/pull/420) and Forms (https://github.com/localgovdrupal/localgov_forms/pull/43).

Once they're approved we'll need to coordinate the 3.0.0-alpha1 releases as composer references will need updating after each release.

I'm happy to say we're almost there.

**Comment by stephen-cox** [comment]
We're ready for an Alpha release!

The following needs to happen in order:

1. 3.0.0-alpha1 release of Microsites Group https://github.com/localgovdrupal/localgov_microsites_group/pull/420
2. Update the Composer reference in the Microsites profile to the 3.0.0-alpha1 release of Microsites Group: https://github.com/localgovdrupal/localgov_microsites/blob/3.x/composer.json#L29
3. 3.0.0-alpha1 release of Microsites https://github.com/localgovdrupal/localgov_microsites/pull/401
4. Update the Composer reference in Microsites project to the 3.0.0-alpha1 release of Microsites: https://github.com/localgovdrupal/localgov_microsites_project/blob/3.x/composer.json#L28
5.  3.0.0-alpha1 release of Microsites Project https://github.com/localgovdrupal/localgov_microsites_project/pull/31

**Comment by finnlewis** [comment]
I think we can close this one. Great work everyone!
