### ISSUE TITLE
Uploading images using Media and text component

### ISSUE THREAD

**Issue by xtianjohnson** [localgovdrupal/localgov_microsites#354]
I have experienced this issue with the Media with text component, as well as others containing a media field. 

I can upload an image successfully but I am unable to save the rest of the form. Even with all the fields completed, it doesn't seem to make a difference.

<img width="725" alt="SelectAndAddMedia" src="https://user-images.githubusercontent.com/110027591/212955015-cd797041-64df-499d-9015-e657086f9d5e.PNG">

**Comment by finnlewis** [comment]
Hi @xtianjohnson !

I am trying to replicate this locally and I can't.

1. Fresh install of localgov_microsites
2. Create user with the microsite controller role
3. Log in to the control site as the microsite controller
4. Create a microsite "site 1"
5. Create a user "admin 1"
6. Assign user the the microsite with the admin role
7. Log  into site 1 as "admin1"
8. Edit the default page
9. Add a "media with text" paragraph 
10. Add a title
11. Click "Add media"
12. Click "browse" to add a new file
13. Select an image
14. Add "Alternative text"


![image](https://user-images.githubusercontent.com/326588/214005612-2315fc54-81e8-41a1-9398-39787997c612.png)

15. Click save 
16. See the new image in the media library

![image](https://user-images.githubusercontent.com/326588/214006729-9a799249-c209-4f57-b34e-ff1dead93007.png)

17. Click "Insert selected"
18. Add some text to the "Content"
19. Click save

![image](https://user-images.githubusercontent.com/326588/214007243-5a6cb134-5a6d-4848-bc02-9b70f790a1c3.png)

At which point does it get stuck for you? 
Are there any other errors? 
Anything in your Drupal log on the control site? 
Anything in the JavaScript console log in the browser?

**Comment by xtianjohnson** [comment]
Hi @finnlewis think we can close this now. looks likes an issue with our local set up. I have tried it on the demo sites and it works fine and I didn't experience the problem.

Many thanks, Christian
