### ISSUE TITLE
Saving site design sends you to dashboard tab

### ISSUE THREAD

**Issue by LizziCBFC** [localgovdrupal/localgov_microsites#359]
Whenever you save a site design, it goes back to the dashboard. 

When testing designs this is frustrating. 

Can the save be set to reload where it is, rather than send you to dashboard?

**Comment by stephen-cox** [comment]
Hi @LizziCBFC, I've created a fix for this issue (localgovdrupal/localgov_microsites_group#386). It will need reviewing so might take a week or before it's released.

**Comment by stephen-cox** [comment]
@LizziCBFC This was fixed with the latest release of Microsites. If you update your installation you should now stay in the site design section when you save any changes.

Thanks for reporting this issue.
