### ISSUE TITLE
Microsites controller - create a new site

### ISSUE THREAD

**Issue by finnlewis** [localgovdrupal/localgov_microsites#36]
## User story

As a microsites overlord 

I want to create a new microsite

So that we can add configuration, users and content to the microsite

## Notes: 

This is currently working but workflow is a bit confusing. We need to tidy up the admin UI.

See example wireframes: 

![image](https://user-images.githubusercontent.com/326588/165480436-b39a3b6d-ec8e-4c15-91e6-f86642963af1.png)

https://miro.com/app/board/uXjVO9o1iRk=/

Initial thoughts: 

Step 1: Create form

Create new group (site) entity - group add form: 

- [x] Remove the 'URL Alias tab
- [x] Remove Revision information tab
- [x] Remove publish toggle (defaulting to published)
- [x] Remove all tabs? 
- [x] Hide header and footer tabs (these will be displayed once we have created it)
- [x] Add the 'hostname' field from the domain to the entity create form.
- [x] Add the email address filed from the domain to the entity create form.

Thus we'd end up with fields: 

- Site name
- Hostname 
- Email address

Questions: 

 - Mark: Do we even need to give it a name? 

Step 2: 

Controller creates:

- [x] Rename 'Domain settings' to 'Site settings'
- [x] Rename 'View' to 'Dashboard' ?
- [x] Rename 'Edit' to 'Site design'
- [x] Hide 'Delete'
- [x] Change name of 'Group' to 'Site'
- [x] Hide group permissions (assuming we don't need them for now)
- [x] Hide 'All entities'
- [x] Hide revisions (for now)
- [x] Rename 'Members' to 'Users'
- [x] Rename 'Nodes' to 'Content' 

## Acceptance tests

1. Log in to the control site.
2. Be forwarded to the list of sites (formerly groups)
3. See 'Add site'
4. Add a new site
5. Add a "Site name"
6. Not see 'Revision information' or 'URL Alias' fields
7. Not see 'published' toggle (default to published - as this is controlled by domain)
8. Not see other things as above
9. Save
10. See the 'dashboard' tab of the site
11. Not see the other things above.

**Comment by ekes** [comment]
![Controller create 2022-05-09 17-15](https://user-images.githubusercontent.com/237186/167441723-52a64858-6821-486f-82cb-d9728eba9046.gif)

**Comment by finnlewis** [comment]
@ekes demonstrated progress on this, but there are still a few things to be taken care:

 - We need a microsites controller role to be able to hide things in admin menu and have the redirection work.
 - Rename tabs as outlined above. 

https://github.com/localgovdrupal/localgov_microsites_group/issues/28

**Comment by finnlewis** [comment]
Hi @ekes 

On this one, a couple of things to do: 

- [ ] Rename 'Edit' tab to 'Site design'
- [ ] Hide or remove the 'Revision Information' tab from the edit form

![image](https://user-images.githubusercontent.com/326588/169810272-127c2ec6-f73e-490f-b76d-f56a3f2bc65f.png)

**Comment by ekes** [comment]
As it's the same code that renames 'view' to 'dashboard' and 'edit' to 'site design' what's happening here? Is it different for you if you select a different tab?
