### ISSUE TITLE
Installation using the web UI wizard causes PHP error

### ISSUE THREAD

**Issue by budda** [localgovdrupal/localgov_microsites#364]
Using a fresh install of the Microsites project with Drupal 9.5.3 and PHP 8.1.13 - I selected the "LocalGov Drupal Microsites" install profile option which resulted in the error:

```An AJAX HTTP error occurred.
HTTP Result Code: 200
Debugging information follows.
Path: /core/install.php?langcode=en&profile=localgov_microsites&id=1&op=do_nojs&op=do
StatusText: parsererror
ResponseText: Error: Class "Drupal\default_content\Event\DefaultContentEvents" not found in Drupal\localgov_microsites\EventSubscriber\DefaultContentImportSubscriber::getSubscribedEvents() (line 56 of /var/www/html/web/profiles/contrib/localgov_microsites/src/EventSubscriber/DefaultContentImportSubscriber.php)```

**Comment by finnlewis** [comment]
Just to confirm I have replicated this locally. 

Why it works on the command line and not in the web UI is an interesting question.

@ekes any idea why "Drupal\default_content\Event\DefaultContentEvents" can't be found? 

We install default_content with https://github.com/localgovdrupal/localgov_microsites/blob/2.1.x/localgov_microsites.info.yml#L41

And we declare use at: https://github.com/localgovdrupal/localgov_microsites/blob/2.1.x/src/EventSubscriber/DefaultContentImportSubscriber.php#L6

Is this something to do with how bootstrapped Drupal is on install?

**Comment by finnlewis** [comment]
This is fixed with the latest beta release: 
https://github.com/localgovdrupal/localgov_microsites/releases/tag/2.1.0-beta3
Thanks @budda and @ekes !!!
