### ISSUE TITLE
PHP version - support for PHP 8.0?

### ISSUE THREAD

**Issue by finnlewis** [localgovdrupal/localgov_microsites#365]
Question on Slack: can we support PHP 8.0, (for a while at least).

It is end of life in 9 months: https://www.php.net/supported-versions.php

**Comment by finnlewis** [comment]
Here's a couple of branches for testing: 

https://github.com/localgovdrupal/localgov_microsites_project/tree/feature/2.x/php-8.0
https://github.com/localgovdrupal/localgov_microsites/tree/feature/2.1.x/365-php-8.0

**Comment by finnlewis** [comment]
@ekes @stephen-cox can you recall any reason we explicitly can't support PHP 8.0 or was it just going with the best current and actively supported PHP version ?

**Comment by ekes** [comment]
Nope. Except for targeting, and testing for, a version of PHP that wouldn't be maintained by the time we release is an additional overhead. Just like you target a version of Drupal that'll be supported for when you expect to launch a site.

**Comment by finnlewis** [comment]
@AWearring you could test with the branches linked to above, but if you can run on PHP 8.1 that would probably be better.

Let us know where you get to on this.

**Comment by finnlewis** [comment]
@AWearring is this still a live issue for you?

**Comment by AWearring** [comment]
@finnlewis No, I managed to get my local upgraded to >8.1
Sorry I forgot to update
