### ISSUE TITLE
Config for microsites domain module needs to be exported or ignored.

### ISSUE THREAD

**Issue by finnlewis** [localgovdrupal/localgov_microsites#371]
@Adnan-cds lots microsites! 

Creating a microsite creates config for the domain record. We'll lose this on the next config deploy unless it is ignored!

This needs looking at.

**Comment by ekes** [comment]
https://www.drupal.org/project/domain_group/issues/3349134

**Comment by ekes** [comment]
Not sure best way to flag this for MM because the Merge is on drupal.org, but... hoping this pings it up.

**Comment by stephen-cox** [comment]
@ekes After checking out the branch from the d.o. issue I get the following error

```
Symfony\Component\DependencyInjection\Exception\ServiceNotFoundException: You have requested a non-existent service "plugin.manager.group_content_enabler". in Drupal\Component\DependencyInjection\Container->get() (line 157 of core/lib/Drupal/Component/DependencyInjection/Container.php).
```

Looks like this service is supposed to get all enabled group plugins.

**Comment by finnlewis** [comment]
@Adnan-cds would like to test this

**Comment by finnlewis** [comment]
@stephen-cox I can't reproduce your error.

Steps I took to test: 

1. Fresh install of microsites.
2. Create controller user
3. Create a couple of microsites.
4. Export config
5. Create a third microsite
6. Export config

See: 
```
+------------+-----------------------------------+-----------+
| Collection | Config                            | Operation |
+------------+-----------------------------------+-----------+
|            | domain.config.group_3.system.site | Create    |
|            | domain.record.group_3             | Create    |
+------------+-----------------------------------+-----------+
```
8. Replace domain_group with 

```
cd web/modules/contrib
rm -rf domain_group
git clone git@git.drupal.org:issue/domain_group-3349134.git domain_group
cd domain_group
git checkout 3349134-group-content-domain
drush updb
drush cr
```
9. create microsite 4
10. drush cex

```
 [notice] The active configuration is identical to the configuration in the export directory (../config/sync).
../config/sync
```

**Comment by stephen-cox** [comment]
This does work for me. For some unknown reason I had Ekes' sandbox checked out for the domain_group module and not the domain_group issue repo.

**Comment by finnlewis** [comment]
@stephen-cox mentioned that we now want to pin the version at https://github.com/localgovdrupal/localgov_microsites/blob/2.1.x/composer.json#LL19C1-L20C1

**Comment by stephen-cox** [comment]
This is fixed. Closing
