### ISSUE TITLE
Site 1 manager - create menu items on site 1

### ISSUE THREAD

**Issue by finnlewis** [localgovdrupal/localgov_microsites#39]
## User story

As a site 1 manager
I want to create menu items on site 1
So that I can add more content and allow people to navigate to it

## Notes

This module seems favourite:  https://www.drupal.org/project/group_content_menu

We're expecting two menus: 

 - site menu
 - utility menu

Make sure to... include this in the install config of the localgov_microsite_group module.... to ensure the menu plugin can be in the group - `/admin/group/types/manage/microsite/content`

Questions: 

- [x] Do we want to set default menu items? 
- [x] How is the menu placed on the page / site / group?
- [x] What do we do with blocks? 
- [x] Do we create default menus for each new site? 

## Acceptance tests

1. Log into site 1
2. Edit menus tab
3. Add link to home page
4. Add link to an external site
5. Log out and see the menu

**Comment by stephen-cox** [comment]
Group Content Menu looks like it will do what we need of if. 

* It adds a `group menus` tab to a group page.
* We can create main and utility menu types that are automatically created when a group is created.
* It will automatically add a home menu link to the main menu.
* It hooks into the Drupal menu system so content can be added to menus when it's being created
* There are blocks we can place on a per group basis

One question is how do we want to place the menus? Menu blocks can be added to the primary and secondary theme regions or we can place them using field.

**Comment by finnlewis** [comment]
Thanks @stephen-cox, sounds good !

I think @markconroy and @ekes are best place to discuss the placement question.... could even render a block in a twig template based on options I imagine... anything to avoid config deployment issues, right?

**Comment by markconroy** [comment]
@stephen-cox don't place the menus anywhere for now, and once we get this merged and I play around with it, we can decide on the approach then.

**Comment by ekes** [comment]
[aside- as I ussume this is for the manager to add manually]
On automatic creation of these - I guess that might be a thing? For the page in a group I'm adding a service to localgov_microsites_group which will create the node and assign it to the group. This I then call at the end of the wizard to add the content. But I figured that with a service it could be (a) used elsewhere (b) extended to clone content into a group, or add other different types of content (like a menu I guess)

**Comment by stephen-cox** [comment]
@ekes groups menus can be created automatically when a group is created. This strikes me as the simplest thing; create 2 menus that are only rendered if there's anything in them, but menu creation could be done as part of the group creation wizard.

It's a simple configuration option that can be turned on or off, so I will leave it turned on for now, but would be easy to turn off.

**Comment by stephen-cox** [comment]
@markconroy There's a PR adding main and utility menus here: https://github.com/localgovdrupal/localgov_microsites_group/pull/16

They still need to be placed on the page. It would be easy enough to place blocks in the primary and secondary menu regions, but these don't look to be rendered the localgov_microsite_base theme

**Comment by finnlewis** [comment]
@markconroy passing this to you to render the menu blocks.

**Comment by stephen-cox** [comment]
I'm adding regions to the theme so will create a PR adding blocks for this

**Comment by stephen-cox** [comment]
Done with https://github.com/localgovdrupal/localgov_microsites_base/pull/11
