### ISSUE TITLE
Demo sites with multiple domains

### ISSUE THREAD

**Issue by finnlewis** [localgovdrupal/localgov_microsites#40]
We're going to need some test sites.

- [x] Decide the default sub-domains
- [ ] Test content for test sites
- [ ] Can we get domain aliases set up? (i.e. a Drupal domain site responding multiple FQDNs )

Any initial thoughts on this @stephen-cox / @ekes following our discussion today?

Note: we'll look at automated demo install at a later stage.

**Comment by finnlewis** [comment]
Can we get DNS set up like: 

*.microsites.localgovdrupal.org point to IP address x.x.x.x 

- [ ] Get access to DNS? (@willguv )

**Comment by stephen-cox** [comment]
@willguv We need the following DNS records adding:

A record: microsites.localgovdrupal.org => 95.216.212.249
AAAA record: microsites.localgovdrupal.org => 2a01:4f9:c010:4b19::1
A record: *.microsites.localgovdrupal.org => 95.216.212.249
AAAA record: *.microsites.localgovdrupal.org => 2a01:4f9:c010:4b19::1

If it's not possible to give use access to add these can you ask Asset ICT to do it?

Thanks,

Stephen

**Comment by finnlewis** [comment]
@willguv ping

**Comment by stephen-cox** [comment]
We now have demo sites:
- https://microsites.localgovdrupal.org/
- https://site1.microsites.localgovdrupal.org/
- https://site2.microsites.localgovdrupal.org/
- https://site3.microsites.localgovdrupal.org/
- https://site4.microsites.localgovdrupal.org/
- https://site5.microsites.localgovdrupal.org/

**Comment by finnlewis** [comment]
@richard-s-rowley here's the issue with demo site urls on it.
