### ISSUE TITLE
Deprecated function: Creation of dynamic property

### ISSUE THREAD

**Issue by AWearring** [localgovdrupal/localgov_microsites#414]
The `autosave_form` module throws the following error

`Deprecated function: Creation of dynamic property Drupal\autosave_form\Form\AutosaveFormBuilder::$_serviceId is deprecated in Symfony\Component\DependencyInjection\ContainerBuilder->createService()`

This can be resolved by applying the following patch:
https://www.drupal.org/files/issues/2023-04-20/autosave_form-dynamic-property-deprecation.patch from https://www.drupal.org/project/autosave_form/issues/3355495

**Comment by finnlewis** [comment]
Thanks @AWearring  - I'll take a look!

**Comment by finnlewis** [comment]
Resolved with https://github.com/localgovdrupal/localgov_microsites/pull/415
