### ISSUE TITLE
Confirm role names for Microsites

### ISSUE THREAD

**Issue by finnlewis** [localgovdrupal/localgov_microsites#43]

**Comment by willguv** [comment]
Are there 3 roles here? If so, does looking at LGD core help?

<img width="588" alt="Screenshot 2022-04-27 at 11 36 51" src="https://user-images.githubusercontent.com/708140/165512708-f3b6d603-03f6-4aff-8271-909d5cd21606.png">

Here's my starter for 10

Microsites manager (the overlord role)
Site editor (the site manager role)
Site contributor (limited editor permissions as needed)

**Comment by finnlewis** [comment]
I think we might want to think about what the current roles in LGD do and what additional roles we need here.

When we bring workflow into the mix, I think you're on the money in that we'll want to match the roles that apply to the default permissions and workflows. Looking at the default install of Localgov Drupal: 

 - Contributor: can create content but not publish
 - Author: can create and publish and archive
 - Editor: can reject / approve / archive / publish / restore / restore to draft

In the Microsites system, these roles are on a group by group / site by site basis, not site-wide.

So, we still need a new roles for the new functions.

Building on your suggestion, how's this?

 - **Microsites manager** (formerly microsites overlord): can create the microsites and manage users on the **control site**
 - **Site owner**:  someone that owns the site and can configure the site and theme options
 - **Editor**: someone that just manages content on the particular microsite. This then maps directly to the editor role in that they can create and manage all content.

If / when we then bring in workflow, we can add Contributor and Author as needed.

Penny for your thoughts @ekes @markconroy @stephen-cox @msayoung @richard-s-rowley

**Comment by finnlewis** [comment]
Once we agree these, we can update the other user stories to match.

**Comment by ekes** [comment]
> Microsites manager (formerly microsites overlord): can create the microsites and manage users on the control site

Site manager. It's too easy to mix owner / admin / manager.
So my best offer is still **controller** role for the **control site**.

> Site owner: someone that owns the site and can configure the site and theme options

It's certainly not owner. That's a thing. That's the Owner UID on the Group entity. There are however more (default terminology) users with the group **Admin** role. So it's a role not a single user.

**Comment by finnlewis** [comment]
![image](https://user-images.githubusercontent.com/326588/165548020-0d0fa0e6-6132-4070-9c4a-f9b9e0f248c4.png)

**Comment by finnlewis** [comment]
So... does this suggest: 

- **Microsites controller** (formerly microsites overlord): can create the microsites and manage users on the control site
- **Site admin**: someone that owns the site and can configure the site and theme options
- **Editor**: someone that just manages content on the particular microsite. This then maps directly to the editor role in that they can create and manage all content.

**Comment by willguv** [comment]
I don’t like controller really - it’s not a word we’ve used before

But then, we haven’t had microsites before, so…

I think we put a proposal to the working group next week

**Comment by ekes** [comment]
I had 

> ![image](https://user-images.githubusercontent.com/326588/165548020-0d0fa0e6-6132-4070-9c4a-f9b9e0f248c4.png)

I had 'control tower' and 'air traffic controller' in mind. Trains it's a signaller or a dispatcher isn't it :-P

> I don’t like controller really - it’s not a word we’ve used before

I think it needs to be a new word. Up till now we'd tried using manager, administrator, but the trouble is it's _very_ easy to forget: "Is that the one that's the one that is the manager/administrator of the site**s** or the individual site".

**Comment by finnlewis** [comment]
We do really need something to work with for this sprint. 

I was hoping we would meet this afternoon and agree that.

So maybe we just stick with "microsites overlord" for now. Not ideal, but at least we know what we mean.

**Comment by willguv** [comment]
I think let's go with this then. I can live with "controller"

We can see how it works for this sprint, and then run it by the working group at a later date

--------

- **Microsites controller** (formerly microsites overlord): can create the microsites and manage users on the control site
- **Site admin**: someone that owns the site and can configure the site and theme options
- **Editor**: someone that just manages content on the particular microsite. This then maps directly to the editor role in that they can create and manage all content

**Comment by finnlewis** [comment]
Note: there is also a **member** role for a user who is part of group/site - equivalent to Authenticated User in Drupal. 

 - we might want to rename it.
 - we might want to hide it.

**Comment by finnlewis** [comment]
At the meeting of the Microsites Working Group yesterday, we agreed on the following role names: 

**Microsites controller** (formerly microsites overlord): can create the microsites and manage users on the control site
**Microsite admin**: someone that owns the site and can configure the site and theme options
**Microsite editor**: someone that just manages content on the particular microsite. This then maps directly to the editor role in that they can create and manage all content

See https://docs.google.com/document/d/1Y63d87PP6gc89m01NjJRUwsLzv5GWxRxDXgRG3-vbM4/edit#heading=h.qcyz8wdhyg68 for notes on discussion.
