### ISSUE TITLE
Provide way of creating short urls

### ISSUE THREAD

**Issue by willguv** [localgovdrupal/localgov_microsites#445]
Editors on the Love Essex website wanted to create short urls for publicity

@markconroy enabled url redirects in the sidebar on pages which content designers could edit as they like

<img width="325" alt="Screenshot 2024-05-28 at 11 41 28" src="https://github.com/localgovdrupal/localgov_microsites/assets/708140/b07c3a7f-f997-4f1f-8f12-aa485b3f050e">

This worked well. We could also consider the quick redirects functionality from LGD which brings all redirects together in one place

**Comment by finnlewis** [comment]
Oooh... I didn't know we could do that! 

So @markconroy is it possible to allow creation of redirects from / to a given node from the node edit form without giving access to the overall manage all redirects page?
