### ISSUE TITLE
Google Calendar Meetings - confirm preferred approach

### ISSUE THREAD

**Issue by finnlewis** [localgovdrupal/localgov_microsites#48]
## Advanced features: 

When I create a meeting in my Open Code account, it has some nice features like recording and raise hand and breakout rooms.

When I create a meeting in the LocalGov Drupal account, it does not have these features.

@willguv @TJHDCR does the Localgov Drupal Google account have these features when you create events? 

## Needing to be let in

There also appears to be a situation I create a meeting and invite lots of people and if I am not there, they need to be let in and the only person who can let them in is me. 

From some initial experimentation, I think that ticking the 'modify event' check box under 'Guest permissions' allows people to join without me, but I am still not 100% on this

![image](https://user-images.githubusercontent.com/326588/165550568-8f38c3c0-f4a7-4b91-8dd2-553ab415f5f4.png)

Any thoughts @willguv @TJHDCR @richard-s-rowley @markconroy ?

**Comment by finnlewis** [comment]
I believe we have a meeting about meetings tomorrow, but do feel free to add ay comments here.

**Comment by finnlewis** [comment]
@TJHDCR @willguv do you have any comments on the above? 

Keen to make sure we all share our understanding and we're all on the same page in terms of meeting scheduling protocol.

**Comment by willguv** [comment]
Hi @finnlewis I don't see meeting record or any of the other features you mention, but perhaps @TJHDCR does?

I think Google Meet features are controlled by the tier of Google Workspace account. LocalGov Drupal Google is "Google Workspace Business Standard"

Would you let me know what your Open Code account is, and we can consider upgrading it. There's only 2 users on it right now (hello@ and will@) so shouldn't be very expensive

I'm not sure if "modify event" does what we need, and we should try it. One big problem is inviting council email addresses, but they're not gmails.

**Comment by ghost** [comment]
Hello. I don't see the record or other features. however i rarely (if ever) log into the account. I have a link with the account from my own google calendar from where i create and modify the events. I always tick "modify event" - this appears to help with people entering without an issue even on a different account - but i can't be sure if that is true. 

I'm about to update the calendar based on previous discussion - but now aware some have multiple events left in calendars because for whatever reason their non google calendar hasn't updated when i have cancelled events. I presuming a solution to a fair bit of this would be using Teams - this may be the best for councils - which really should be our focus.

**Comment by finnlewis** [comment]
this helps to explain how it works: 
https://support.google.com/meet/thread/33894007?hl=en&msgid=33911155

> 
> * Someone signed into an account from inside your organization, on the same G Suite domain, can join directly
> * Someone who is invited directly to the event on Google Calendar, and who is signed into Google with the invited email, can join directly
> * Everyone else must ask to join
>  
> There isn't any way to change that setting. 
> Learn more here: https://support.google.com/meet/answer/9303069

That last link does seem to cover it.

So the upshot is, if we create an event we need to make sure someone else from our organisation is present to let people in.

Maybe we should set up accounts for tim@ and finn@ as well as will@ so that we can always create meetings in the localgovdrupal.org Google account and ensure at least one of us will always be present at a meeting? 

I use the 'Business standard' with Open Code, which gives access to recording and perhaps some of those extra meeting tools. 

Here's the pricing @willguv https://workspace.google.com/pricing.html

**Comment by finnlewis** [comment]
I'll pass this over to you @willguv to assess and decide.

**Comment by finnlewis** [comment]
@willguv any time to review this?

**Comment by willguv** [comment]
Sorry @finnlewis I missed this in the flurry of other notifications

We're already on Business Standard 

These two users already exist

hello@localgovdrupal.org used by Tim
will@localgovdrupal.org used by me

So we'd need to set one up for finn@ - happy to do that. If you agree I can get that done today

**Comment by finnlewis** [comment]
Hi @willguv - happy to have a finn@localgovdrupal.org and create events / meetings using that account.

**Comment by willguv** [comment]
@finnlewis I think our move to Zoom for most meetings supersedes this conversation, so closing. Hope OK
