### ISSUE TITLE
Visual design for primary theme

### ISSUE THREAD

**Issue by finnlewis** [localgovdrupal/localgov_microsites#52]
This was a draft card which I've just converted to an issue for discussion.

@markconroy you suggested that a certain amount of the styling / theme will just follow the default localgov_base theme. 
@richard-s-rowley have you been thinking about designing an initial theme / or themes for demonstration purposes? 

I think this will emerge out of necessity, but let's collate thoughts here and confirm what tasks there are for this sprint or the next. It would be good to have something looking really good, and perhaps a bit different from Localgov Drupal core, ready for some testing in sprint 4.

**Comment by finnlewis** [comment]
Noting that there are at least three 'vibes' of site design.

Initially we're inheriting from LocalGov Base = council vibe.

So we'll park this design issue for now to see what we get out of the variable configuration options.

**Comment by richard-s-rowley** [comment]
- vibes
- typography
- simple colour options
- accessibility
- spacing options
- sizing options

**Comment by richard-s-rowley** [comment]
Suggested font families for testing: https://miro.com/app/board/uXjVOStMNW8=/?moveToWidget=3458764524625161432&cot=14
