### ISSUE TITLE
Test: do site owner/admins need to be able to add users themselves?

### ISSUE THREAD

**Issue by richard-s-rowley** [localgovdrupal/localgov_microsites#53]
At present, the controller has to add all users. How high a priority is changing that behaviour?

cc @ekes @markconroy

**Comment by markconroy** [comment]
I think this will become an issue fairly quickly if a council has multiple sites. I reckon we'll see small sites not wanting to have a change request process to add a new editor.

**Comment by keelanfh** [comment]
This was done.
