### ISSUE TITLE
Site 1 admin - configure the site design for site 1.

### ISSUE THREAD

**Issue by finnlewis** [localgovdrupal/localgov_microsites#55]
## User story

**As a** site manager 

**I want to** log in to my new site 1 

**So that I can** change the site design

## Notes 

The site has been created by the controller.
The controller has added the user and added the user to the site
The site 1 manager has logged into the site for the first time.

![image](https://user-images.githubusercontent.com/326588/165744772-c1d919d5-a070-4d35-b333-9d9d08cd0e49.png)

We're looking at getting all these 55 / 60 options actually working in this sprint.

Questions: 

- [ ] What are the names of the groupings?
- [ ] What does it look like? 
- [ ] Are there examples of this elsewhere? 
- [ ] Do we want a restricted palette? 
- [x] Do we want a colour picker? 

## Acceptance tests

1. Site manager 1  logs in to site 1
2. Click on the **site design** (formerly edit) tab
3. Edit each option on the site design tab
4. Save
5. Go to site1 url
6. See the changes take effect.

**Comment by finnlewis** [comment]
Mark has the approach worked out and demonstrated progress at sprint review.

Still work to do next sprint!

**Comment by finnlewis** [comment]
@markconroy I wonder can we split this one up into smaller tasks?

**Comment by finnlewis** [comment]
Split this into 

- Header
- Footer
- Typography
- Spacing

**Comment by markconroy** [comment]
Let's close this since we have the micro issues created for it instead.
