### ISSUE TITLE
Site 1 admin - create directories in microsite 1

### ISSUE THREAD

**Issue by finnlewis** [localgovdrupal/localgov_microsites#57]
## User story

As a 'site admin' on microsite
I want to create directory channels and directory entries 
So that we can deploy a searchable directory of locations on a microsite.

## Notes: 

We think this might actually be easier than adding localgov_events into the microsites install.

## Possible complications: 
 - seach_api with group content -> which are we showing, the group content relationship or the actual node with the content
 - access control on the node might help with the above

## Assumptions: 

We are adding localgov_directories as is to microsites, no change in functionality.

We will separate off the issues of: 
 - restricting which content types are available to each microsites
 - we allow all facet types to be accessible across all microsites: later we might want to restrict these per group

## Acceptance tests: 

Setup: controller: 
 - creates a new microsite 'microsite 1'
 - creates and assigns a new user to the site as a microsite admin

As 'microsite 1 admin'

1. Log into site
2. Create directory channel
3. Create several directory entries
4. Log out
5. Search
6. Filter
7. Smile

**Comment by stephen-cox** [comment]
There are 3 PRs associated with this:

- https://github.com/localgovdrupal/localgov_microsites_group/pull/106
- https://github.com/localgovdrupal/localgov_microsites/pull/145
- https://github.com/localgovdrupal/localgov_microsites_base/pull/41

To make it easier for testing you can checkout the `feature/57-directories` branch on the project (https://github.com/localgovdrupal/localgov_microsites_project/tree/feature/57-directories) and run a composer install.

**Comment by stephen-cox** [comment]
The work so far has been deployed to https://microsites.localgovdrupal.org/ for testing.

Example directories:

- https://site1.microsites.localgovdrupal.org/colours
- https://site2.microsites.localgovdrupal.org/other-colours
