### ISSUE TITLE
Microsites audit - complete the audit of microsites from partner councils

### ISSUE THREAD

**Issue by finnlewis** [localgovdrupal/localgov_microsites#6]
We'd like to identify which existing microsites we are aiming to serve with the microsites product.

Tasks: 

- [ ] Remove sites that are out scope from the big list.

- [ ] Identify a litmus site for each council involved.

**Comment by willguv** [comment]
@msayoung asked about Local Offer legislation - see https://www.legislation.gov.uk/ukpga/2014/6/section/30/enacted

**Comment by msayoung** [comment]
The Big List: https://docs.google.com/spreadsheets/d/1V4TRtUCTC6bJAtcd34TbaegzOlrM5Hcn6HERPMr-A4o/edit#gid=0

Litmus sites: https://docs.google.com/spreadsheets/d/1V4TRtUCTC6bJAtcd34TbaegzOlrM5Hcn6HERPMr-A4o/edit#gid=615037482 

And then the following tabs have those sites compared by various criteria
