### ISSUE TITLE
Set default blocks

### ISSUE THREAD

**Issue by ekes** [localgovdrupal/localgov_microsites#61]
When installing the profile - or when installing the theme?

**Comment by finnlewis** [comment]
- [x] Review block placement in theme templates to ensure regions are rendered.
- [x] Place default blocks on install (title, content, messaging, menus etc.)

@markconroy could you confirm any specifics that need thought?

**Comment by finnlewis** [comment]
@stephen-cox while looking at this, @ekes has added a block of admin links for the microsite admin on a site, to be able to get quickly back to manage content . users etc. 

https://github.com/localgovdrupal/localgov_microsites_group/blob/1.x/src/Plugin/Block/MicrositeTasksBlock.php

It would be good to have this placed somewhere appropriate. Above the header perhaps?

**Comment by markconroy** [comment]
It's probably worth placing it in the "tabs" region, and we can style it the same as the tabs

**Comment by stephen-cox** [comment]
This PR places the Microsite Task block in the tabs region: https://github.com/localgovdrupal/localgov_microsites_base/pull/11

**Comment by markconroy** [comment]
That's merged now @stephen-cox
