### ISSUE TITLE
Test sites setup for user testing - domains / installs

### ISSUE THREAD

**Issue by finnlewis** [localgovdrupal/localgov_microsites#65]
We'll be testing with at least 5 councils.

1. Waltham Forest
2. Croydon
3. Blackburn
4. Wirral
5. Bath and NE Somerset

Each council will have 2-3 users.

Do we set up a separate sites for each council and persist?  

- [x] Confirm the number of sites
- [x] Confirm site domains
- [x] Add DNS records for each
- [x] Set up server
- [x] Set up automation to help manage these (reinstall etc)

**Comment by stephen-cox** [comment]
@richard-s-rowley @finnlewis @willguv Assuming we will only need 1 test site per council (so if users from the same council are testing the site at the same time they're doing it together) then I propose the following controller sites:

- bathnes.localgovdrupa.org
- blackburn.localgovdrupa.org
- croydon.localgovdrupa.org
- walthamforest.localgovdrupa.org
- wirral.localgovdrupa.org

With the ability to create microsites as subdomains of these; e.g site1.bathnes.localgovdrupa.org and events.wirral.localgovdrupa.org.

Are there any other councils that may be testing stuff? If so, it will be easier to get this set up now.

Does the basic naming system sound okay? This provides some limits on the testing, but gives each council their own site to play with.

**Comment by finnlewis** [comment]
Yes, this sounds perfect @stephen-cox , apart from the (intentional?) typo, missing the 'l' off localgovdrupal.org !

Maybe do one for Cumbria too, just in case?

**Comment by stephen-cox** [comment]
One thing I've just realised is to use HTTPS I'll need to know the subdomains beforehand so I can add them to the certificate, otherwise you'll get certificate errors; although that might be fine for testing.

**Comment by stephen-cox** [comment]
@willguv Are you able to get the following DNS records setup?

## Jenkins - New automation server

A record: jenkins.localgovdrupal.org => 135.181.27.123
AAAA record: jenkins.localgovdrupal.org => 2a01:4f9:c011:ba5c::1

## Web 1 - Current localgovdrupal.org web server

A record: web1.localgovdrupal.org => 95.216.212.249
AAAA record: web1.localgovdrupal.org => 2a01:4f9:c010:4b19::1

## Web 2 - New testing server

A record: web2.localgovdrupal.org => 135.181.28.137
AAAA record: web2.localgovdrupal.org => 2a01:4f9:c011:ba5d::1
CNAME record: bathnes.localgovdrupal.org => web2.localgovdrupal.org
CNAME record: *.bathnes.localgovdrupal.org => web2.localgovdrupal.org
CNAME record: blackburn.localgovdrupal.org => web2.localgovdrupal.org
CNAME record: *.blackburn.localgovdrupal.org => web2.localgovdrupal.org
CNAME record: croydon.localgovdrupal.org => web2.localgovdrupal.org
CNAME record: *.croydon.localgovdrupal.org => web2.localgovdrupal.org
CNAME record: cumbria.localgovdrupal.org => web2.localgovdrupal.org
CNAME record: *.cumbria.localgovdrupal.org => web2.localgovdrupal.org
CNAME record: walthamforest.localgovdrupal.org => web2.localgovdrupal.org
CNAME record: *.walthamforest.localgovdrupal.org => web2.localgovdrupal.org
CNAME record: wirral.localgovdrupal.org => web2.localgovdrupal.org
CNAME record: *.wirral.localgovdrupal.org => web2.localgovdrupal.org

If the wildcard CNAME records are not supported by the DNS provider then the CNAME record will need replacing with the same A and AAAA records are the web2 server.

Thanks Stephen

**Comment by willguv** [comment]
@stephen-cox should be done, please check. Thanks

**Comment by finnlewis** [comment]
Update: DNS in place, @stephen-cox is setting up the server for this and a Jenkins server!

**Comment by stephen-cox** [comment]
We have the following sites:

- https://bathnes.localgovdrupal.org/
- https://blackburn.localgovdrupal.org/
- https://blackburn.localgovdrupal.org/
- https://blackburn.localgovdrupal.org/

-

**Comment by stephen-cox** [comment]
We have the following sites:

- https://bathnes.localgovdrupal.org/
- https://blackburn.localgovdrupal.org/
- https://croydon.localgovdrupal.org/
- https://walthamforest.localgovdrupal.org/
- https://wirral.localgovdrupal.org/

Each have SSL certs for the subdomains: site1, site2, site3, site4, and site5. Others can be added as required.

There's a Jenkins server which allows people to run stuff on all the different sites hosted by Agile Collective (https://jenkins.localgovdrupal.org/). Authentication is done via GitHub. Any member of the localgovdrupal organisation can run jobs. @stephen-cox @finnlewis and @ekes are admins, All jobs are managed in https://github.com/localgovdrupal/jenkins_config/

The Jenkins stuff needs improving, documenting and security reviewed, but should do for the time being.

**Comment by finnlewis** [comment]
Great work @stephen-cox ! 

I've logged into the Croydon site as the 'LocalGov Controller' and it all seems to be working nicely,

Exciting!

**Comment by finnlewis** [comment]
I think this one is done, feel free to re-open if needed.

**Comment by willguv** [comment]
Nice work!!
