### ISSUE TITLE
Default 'microsites controller' user for the user testing

### ISSUE THREAD

**Issue by finnlewis** [localgovdrupal/localgov_microsites#66]

**Comment by stephen-cox** [comment]
As part of the initial site install run through Jenkins (https://jenkins.localgovdrupal.org/) for a microsite a controller user is now added:

https://github.com/localgovdrupal/jenkins_config/blob/1.x/jenkins_jobs.groovy#L189-190

The login details for this are:

Username: LocalGov Controller
Password: 3Z3BNSYe1Lf7Zs

**Comment by finnlewis** [comment]
Just to avoid confusion, this is the username and password for the default user set up on each site with the 'Microsites controller' role. 

It does not provide access to Jenkins. 

Access to Jenkins is governed by single sign on with GitHub (very neat!)
