### ISSUE TITLE
Define and implement the default page content (headings and components)

### ISSUE THREAD

**Issue by finnlewis** [localgovdrupal/localgov_microsites#67]
@stephen-cox to create demo sites

@markconroy  / @richard-s-rowley to create a page with headings and content

@ekes to wrap this up into the default page when a microsite gets created

(Note long term we might want to clone a node)

**Comment by finnlewis** [comment]
I guess @stephen-cox as soon as we have a demo site that @markconroy and @richard-s-rowley can log into, they can create the node with appropriate headings / text / images for wrapping up.

**Comment by stephen-cox** [comment]
@finnlewis @markconroy @richard-s-rowley There's a demo site ready for an example page that can be deployed with each testing microsite: https://microsites.localgovdrupal.org/

Login details are in Slack: https://localgovdrupal.slack.com/archives/C037BR1DY8N/p1652801970314359

I have created a microsite which comes with a default front page, so might be easiest to edit that: https://microsites.localgovdrupal.org/node/1/edit

I haven't enabled any extra paragraph types for use on that page. They can be enabled here: https://microsites.localgovdrupal.org/admin/structure/types/manage/localgov_page/fields/node.localgov_page.localgov_page_content. I can do this if you let me know which ones you want.

**Comment by finnlewis** [comment]
Yes, paragraph types! 

What do we already have at our disposal? 

How many can we add that would be valuable and good to test? 

Should we start another issue for adding paragraphs? 

CC @msayoung

**Comment by richard-s-rowley** [comment]
These are the Paragraph types we earmarked as Musts or Shoulds:

text  
image  
video  
button  
quote  
table  
attachments  
embed block view  
accordions  
Promo blocks [featured teasers]  
call-out box  
media with text  
IA block  

We also suggested two new Paragraphs:
media  
slider of things  

We might also enable in other LGD ones but seeing whether people can do what they want with the ones above might be better for testing.

**Comment by stephen-cox** [comment]
I have added the paragraph types apart from button (I can't see this listed in the available types)

**Comment by finnlewis** [comment]
Where are we adding the paragraph types @stephen-cox ?

**Comment by stephen-cox** [comment]
If these are paragraph types that will be deployed with every page install (in LocalGov and Microsites) then config should live in localgov_page. If it's mircosites specific then it should live in localgov_microsites.

**Comment by finnlewis** [comment]
I think for now let's keep it all in localgov_page, even if that means a dependency on [localgov_subsites_paragraphs](https://github.com/localgovdrupal/localgov_subsites/tree/2.x/modules/localgov_subsites_paragraphs/) for now to get all the paragraphs we want. Currently localgov_page is only for the microsites project, so it is safe make that call for now.  

We can look at refactoring the wider paragraph dependency chain later.

**Comment by finnlewis** [comment]
On the paragraphs tip, I've started an issue and pull request here: 
https://github.com/localgovdrupal/localgov_page/issues/1
https://github.com/localgovdrupal/localgov_page/pull/2

**Comment by finnlewis** [comment]
So @richard-s-rowley  and @msayoung have been building out content on https://site1.microsites.localgovdrupal.org/node/1

Once this has examples of all the components, probably best to pass to @stephen-cox to look at wrapping it up into a default content t - probably with https://www.drupal.org/project/default_content I guess.

**Comment by richard-s-rowley** [comment]
Passing to you @stephen-cox to wrap it up
