### ISSUE TITLE
Site design: styleguide tab

### ISSUE THREAD

**Issue by finnlewis** [localgovdrupal/localgov_microsites#68]
@markconroy has done a bunch of work on this: 

Still todo: 

- [x] add secondary colour
- [x] font weight for headings
- [x] base spacing
- [x] rename to 'Global styles'

**Comment by msayoung** [comment]
Wasn't sure what everything should do so:

- Primary colour: default colour for header and footer background and link text
- Secondary colour: default link **hover** colour on the header and footer
- Heading font:
- Body font: 
- Text colour (light) : default text colour on the header and footer
- Text colour (dark) : default text colour 
- Base font size
- Base line height
- Base spacing: sets the base space unit, which is applied variously across the site

**Comment by markconroy** [comment]
The base space unit in `localgov_base` is `--spacing` which equates to `1rem`. 

I had imagined that's what we'd set our base space unit to as well. Meaning, in our `localgov_microsites_base` theme, we'd evaluate `--spacing` to whatever value was input in the Base Spacing field. Then we shouldn't need this part of the PR:
``` /* Widths and Spacing */
  --spacing-smallest: calc(var(--base-spacing)/4);
  --spacing-smaller: calc(var(--base-spacing)/2);
  --spacing-small: calc(var(--base-spacing)*0.75);
  --spacing: var(--base-spacing);
  --spacing-large: calc(var(--base-spacing)*1.5);
  --spacing-larger: calc(var(--base-spacing)*2);
  --spacing-largest: calc(var(--base-spacing)*2.5);
  --spacing-mega: calc(var(--base-spacing)*3);
  --vertical-rhythm-spacing: calc(var(--line-height) * var(--base-spacing));
```

**Comment by markconroy** [comment]
And now, after looking at `localgov_base` that's not how we have it done. 

@msayoung I think we should make a PR for the code block above to become part of the `localgov_base` repo, and not the localgov_microsites_base repo, so that will keep that repo/css as small as possible.

**Comment by finnlewis** [comment]
So what's to do on this one and is it with @msayoung or @markconroy ?

**Comment by markconroy** [comment]
Let's mark this as "done". There's a small follow up issue to remove the defaults from 2 fields.
