### ISSUE TITLE
Review and report on Annertech's existing solution as a case study

### ISSUE THREAD

**Issue by finnlewis** [localgovdrupal/localgov_microsites#7]
Produce concise case study: 

How hard is it to set up a new site? 
Does it have flexibly over look and feel theme
Does it have separation of content editors and permissions?
What is the technical architecture?
Pros and cons?

**Comment by markconroy** [comment]
Done here: https://docs.google.com/document/d/13MBOcExiNyyVP_qBeJ16x0rw4QY54ua5Vy347lI3DHs/edit#

And added to Miro board.
