### ISSUE TITLE
Site design: footer content

### ISSUE THREAD

**Issue by finnlewis** [localgovdrupal/localgov_microsites#71]
This contains the content for the footer.

banner, block 1,2,3,4

Todo: 

- [x] check how the layouts behave if fewer blocks have content
- [x] footer logo with media field
- [x] delete the housekeeping menu
- [x] add separate housekeeping menu
- [x] change copyright to text field
- [ ] add more help text

**Comment by msayoung** [comment]
@finnlewis are you sure we want the copyright field as a text field. 
Currently it'll automatically change year
and if they want different text they can put it in one of the other text fields

**Comment by finnlewis** [comment]
We discussed it and that was the decision at the time, so yes, let's stick to it I reckon.

[aside]
Personally I think copyright notices on websites are pointless. Maybe even more so on public sector websites! (what does it mean to 'steal' content that is in the public domain funded by public money?) 

Although I do now understand that open source licencing relies on copyright law to subvert it.

**Comment by msayoung** [comment]
Once the PRs are merged perhaps we can review the help text @finnlewis ?

**Comment by msayoung** [comment]
Ok - I suggest closing this and opening another about help text - ok with you @finnlewis ?
