### ISSUE TITLE
Site design: footer design

### ISSUE THREAD

**Issue by finnlewis** [localgovdrupal/localgov_microsites#73]
Mark has built out the form.

This has overrides for each colour and header width behaviour.

Todo: 

- [x] review the styling of the footer with respect to the fields.
- [x] maybe add colour picker?
- [x] check language of the footer layout.

**Comment by msayoung** [comment]
@finnlewis - having a look at this, I'm not sure I understand what is needed? 

(I'm assuming you mean footer when you say header)

**Comment by finnlewis** [comment]
We created each of these 'site design' issues to spilt out the work to check that the theme responds appropriately to changing values in the configuration.

In this case, I think editing each field that affects the footer, and see how it plays.

We also mentioned the colour picker widget on all colour fields, which was originally an assumption of mine, but on discussion was generally agreed to be a nice thing to have and would not prevent entering other css values into the text field.

**Comment by msayoung** [comment]
@finnlewis when you say "check language of the footer layout." do you mean the help text ?

**Comment by finnlewis** [comment]
I'm not sure, possibly how the layout options are described? @markconroy @richard-s-rowley do you recall what we mean by "git@github.com:localgovdrupal/localgov_microsites.git" ?

**Comment by markconroy** [comment]
I think we meant the specific words we used for the layout options: 'full width', 'full with with content contained', etc

**Comment by msayoung** [comment]
How about?

- Background and content full width
- Background full width, content constrained
- Background and content constrained

**Comment by msayoung** [comment]
@finnlewis what do you think about the suggestion for the words


- Background and content full width
- Background full width, content constrained
- Background and content constrained

**Comment by markconroy** [comment]
I like those suggestions

**Comment by finnlewis** [comment]
Sounds great for now, we'll get some feedback from the testing I'm sure,

**Comment by msayoung** [comment]
PR here for field labels: https://github.com/localgovdrupal/localgov_microsites_group/pull/80
