### ISSUE TITLE
Dashboard: override the output of the microsite view display to show useful information about the microsite

### ISSUE THREAD

**Issue by finnlewis** [localgovdrupal/localgov_microsites#77]

**Comment by ekes** [comment]
Suggestion: add view of last 5 bits of content. More link to group content page.

Question: should this be a view block; placed by the profile. Or an extra field view embed configured within the module?
This is in the _admin_ theme, so not sure if we're planning on overriding it or anything.

@markconroy @msayoung @finnlewis -- thoughts?

**Comment by finnlewis** [comment]
A block placed with profile probably quickest for now. 

I think we might want some other intro / help text there too. Maybe we can do that with a custom block or some such too.

"This is the dashboard for your microsite. Use the tabs above to manage configuration, styles, content and users. Click the Tour link if you would like more help"

.. sort of thing? 

Longer term, maybe we make this a more configurable set of optional widgets with lots of great summary information about your microsite?

**Comment by ekes** [comment]
> A block placed with profile probably quickest for now.

If time is the only question then the embedded view is quickest - I have all that extra fields stuff templated up and can just roll it out.
