### ISSUE TITLE
Helptext: adding users to microsites

### ISSUE THREAD

**Issue by finnlewis** [localgovdrupal/localgov_microsites#78]
I think we're going to need to add help text in a few places.

One bit of admin UX that is immediately confusing is adding a user to a microsite.

We add the site, then go to the 'Users' tab (https://localgov-micro.lndo.site/group/1/members) we see 
![image](https://user-images.githubusercontent.com/326588/168797314-87662ed1-cd92-4966-a608-8f2fdec37d6e.png)

But to add a user to the microsite, the controller first needs to create a user at https://localgov-micro.lndo.site/admin/people

So, until this changes, we should add some help text. 

For example: 

"To add users to the microsite, they must first exist in Drupal. To create new users, go to /admin/people, then return here to assign users to the microsite."

Questions: 

1. Is this inline help text? 
2. Were should this go on the page above? 
3. Can the Tour module help with this? 

Any thoughts @msayoung @richard-s-rowley @markconroy ?

**Comment by msayoung** [comment]
![image](https://user-images.githubusercontent.com/3852805/168858615-ea771cfc-8fd9-4edb-aa9c-65c1dbb7f71f.png)

**Comment by msayoung** [comment]
A tour might be fun. just had a play - obviously with better words

![image](https://user-images.githubusercontent.com/3852805/168861768-3452a7c5-f6cc-405e-a843-c8f9c9dd4d80.png)
![image](https://user-images.githubusercontent.com/3852805/168862454-2c05a804-9a09-488f-9c99-d767521a7671.png)

**Comment by msayoung** [comment]
whatcha think @finnlewis ?

**Comment by finnlewis** [comment]
That looks great @msayoung ! I realise now that the beauty of Tour is that the user gets to see the help text first time (and again later if they want I think?) meaning the help text does not get in the way of day to day UX.

Is it quick enough to whip up a Tour for any given page?

**Comment by richard-s-rowley** [comment]
@msayoung @finnlewis a Tour is a great idea, as is the help text you added

I think we also need a clear set of instructions somewhere that people can go back to. For now, would the default page work for this? Or another page with a helpful title such as 'Guidance'

**Comment by msayoung** [comment]
I've added a few placeholder tours, the words are not correct by any means, so could do with some help to get that right. 

Also waiting for some of the UI elements to get finalised before pointing to them.

**Comment by markconroy** [comment]
That's a great idea to use tour module @msayoung

**Comment by finnlewis** [comment]
I think this is done for now @msayoung - closing, feel free to re-open if needed.
