### ISSUE TITLE
Help text: first login for controller, explain the microsites listing page

### ISSUE THREAD

**Issue by finnlewis** [localgovdrupal/localgov_microsites#79]
When a 'Microsites controller' first logs in, they will (hopefully) be redirected to the /admin/microsites page.

It would be good to give them some help the first time they log in.

@msayoung are we thinking Tour for this for now?

**Comment by msayoung** [comment]
Sure

So guidance on how to 

- Set up a domain
- Create a microsite 
?

Question: 

If I am a "microsite admin" on more than one site and I visit _/admin/microsites_ on Site A I can see and edit all the microsites. Is this the desired functionality?

**Comment by finnlewis** [comment]
Not sure.... @ekes any thoughts?

**Comment by finnlewis** [comment]
Did we cover this with one of the Tour's @msayoung ?

**Comment by finnlewis** [comment]
I don't think there is a tour for /admin/microsites unless I'm being dense! 
It would be good to add one.
@msayoung OK to leave this with you?

**Comment by msayoung** [comment]
there already was one, but i've updated it now:

https://github.com/localgovdrupal/localgov_microsites_group/pull/53
