### ISSUE TITLE
Microsite admin cannot manage menu items

### ISSUE THREAD

**Issue by msayoung** [localgovdrupal/localgov_microsites#82]
As a microsite admin I can see the Group menus tab, but cant add or manage menu items.

**Comment by msayoung** [comment]
![Image](https://user-images.githubusercontent.com/3852805/169088145-9893ab74-82f6-46f3-a7c6-66017e53342a.png)


![Image](https://user-images.githubusercontent.com/3852805/169088196-af45ef4c-67f0-48a5-ba98-7d293b6e2a3c.png)

**Comment by ekes** [comment]
Have you run compser update recently? Has the patch in localgov_microsites_group https://github.com/localgovdrupal/localgov_microsites_group/blob/fdc05ff08196ce65aa2e8f09050c8f2b82bbe4aa/composer.json#L21 applied?

**Comment by finnlewis** [comment]
I just did a fresh install following https://github.com/localgovdrupal/localgov_microsites_project#readme

I don't think it applies the patch @ekes

**Comment by finnlewis** [comment]
I lie! 
It does!
```

  - Applying patches for drupal/field_group
    https://www.drupal.org/files/issues/2020-06-15/3059614-37.patch (Fix 'Undefined property: stdClass::$region' error #3059614)

```

**Comment by finnlewis** [comment]
I think this does work on a fresh install!

![Image](https://user-images.githubusercontent.com/326588/169095385-5e001bec-b925-4481-8b12-406a573f8ad0.png)
