### ISSUE TITLE
Layout Paragraphs 2.x - significantly better UX

### ISSUE THREAD

**Issue by finnlewis** [localgovdrupal/localgov_microsites#84]
The UX is so much better in layout paragraphs 2.x. 

I wanted to explore whether we might want to get this in for testing with users next week.

This might take a few prongs, localgov_subsites and localgov_page.

I've created a PR for branch I was experimenting with a few months ago.

See https://github.com/localgovdrupal/localgov_subsites/issues/57
and https://github.com/localgovdrupal/localgov_subsites/pull/85

Need to fix some schema errors there on the PR, but also interested in thoughts from others @ekes @stephen-cox @markconroy  @msayoung @richard-s-rowley

**Comment by finnlewis** [comment]
@stephen-cox I'd love to get this lined up for testing if we can. 

What are your thoughts? 

Could just use the branch on  https://github.com/localgovdrupal/localgov_subsites/tree/feature/2.x/57-layout-paragraphs

**Comment by finnlewis** [comment]
@richard-s-rowley @msayoung could you elaborate on the UX and accessibility improvements?

**Comment by msayoung** [comment]
Assigning myself to this to do some a11y testing. I will report back

**Comment by finnlewis** [comment]
It's be good to pipe up on this issue to share our thoughts and perhaps create new issues in the project issue queue if we think changes should be made to the UX in the module: https://www.drupal.org/project/layout_paragraphs/issues/3220933

**Comment by msayoung** [comment]
Ok, I've done some testing with versions 1 & 2, in both Gin and Claro. 

My overall summary is that there are fewer serious issues with version 1, so I think we should go with that for now. 

[Accessibility Log for the UI](https://docs.google.com/spreadsheets/d/1aatEaarNqF8mvt5Mz6tYUHEPHPJsyfggeGKdeA68atY/edit#gid=1745494127
)

[Screenshots](https://docs.google.com/document/d/1l6ULa30Yfzkmq66hhUMiB8qXznow6Dfg-FajFwdO3pM/edit#)

@finnlewis

**Comment by finnlewis** [comment]
Thanks @msayoung - great stuff! 

I totally see the safety and attraction of sticking with Layout Paragraphs 1.x for now. 

I would also like to itemise the issues that we'd need to address to be in a position to use Layout Paragraphs 2.x. 

I'll see if I can expand on what you've done so far.

**Comment by finnlewis** [comment]
@msayoung and @finnlewis are going to review this and itemise the issues.

**Comment by finnlewis** [comment]
Related pull requests:

 - https://github.com/localgovdrupal/localgov_microsites/pull/97
 - https://github.com/localgovdrupal/localgov_subsites/pull/85
