### ISSUE TITLE
Default permissions to upload media

### ISSUE THREAD

**Issue by finnlewis** [localgovdrupal/localgov_microsites#88]
As a microsite admin
I want to upload images and other media
So I don't get the sack

But: 

@ekes @stephen-cox @markconroy @msayoung 

At the moment, the microsite admin cannot upload media.

It seems to me that the 'authenticated user' is the only site-wide role that the microsite admin gets. 

They also get extra permissions in the group permissions, see https://github.com/localgovdrupal/localgov_microsites_group/blob/1.x/config/install/group.role.microsite-admin.yml

Now, do these group permissions depend on the authenticated user having certain permissions? It seems 'yes' for the 'view admin theme' permission.

What about uploading media? 

The quickest way I found to get the 'microsite admin' role to have the permission to upload media was to add it to the 'authenticated user' role. See https://github.com/localgovdrupal/localgov_microsites/pull/87/files

But if we do need to add certain permissions to the 'Authenticated user' role, maybe we should set up a new role for all 'microsite users' or something, to avoid sullying the 'Authenticated user' role which might be needed later for other less trusted users.

For now, let's just get it working, but longer term, thoughts?

**Comment by finnlewis** [comment]
@ekes these were my thoughts yesterday ^^

**Comment by ekes** [comment]
So from #87 it seems the user needs 'edit any image media' https://github.com/localgovdrupal/localgov_microsites/pull/87#issuecomment-1133051905
This would mean that a user with said permission can edit the media on any site, created by anyone.

So while create and edit own etc. would be fine, even though they end up in the global rather than be domain or group restricted. Just as taxonomy terms for example. Editing someones else's isn't good. We'll need a fix for that.

**Comment by ekes** [comment]
https://www.drupal.org/project/groupmedia -- first hit by the way.

**Comment by finnlewis** [comment]
Want to take a look at groupmedia @ekes ?

**Comment by msayoung** [comment]
I just tested this and I could upload media as a Microsite admin

**Comment by stephen-cox** [comment]
I've created a related issue to discuss a `microsite admin` role for permissions like this #144

**Comment by ekes** [comment]
Tell me if I'm wrong but I'd say we've solved this - as well as in any case.
