### ISSUE TITLE
Wrap up the default node to be able to deploy each time a microsite is created.

### ISSUE THREAD

**Issue by finnlewis** [localgovdrupal/localgov_microsites#91]
We want a default node, such as being created on:

https://microsites.localgovdrupal.org/node/1/edit?destination=/admin/content

It would be good to be able to deploy a default node with lots of paragraphs into each microsite.

@ekes already has some ideas!

Entity clone?
Entity replicate?
Migrate?
https://www.drupal.org/project/quick_node_clone

**Comment by finnlewis** [comment]
@ekes testing merge, then this will be done.

**Comment by msayoung** [comment]
amazing! closing
