### ISSUE TITLE
Microsite Admin: Add user ( Streamline adding users to microsites)

### ISSUE THREAD

**Issue by ekes** [localgovdrupal/localgov_microsites#92]
Note: we're just planning to find out which route to take on this issue.

Questions:-

 * Where do users get added? Are we still always administering the site on the microsite, not control domain.
 * Does the admin get to add _existing_ users, and/or _new_ users.

Detail:-

### Group Invite

The most obvious one is [Group invite](https://drupal.org/project/ginvite) which makes a new group content type that handles inviting new group members by email address.
If the user - with the same email - already exists in the system they get a link to just join the group.
If there is no user in the site with the email they get a create user link.
There's no permission differentiation for inviting existing users, or new users, and there's nothing to say if the user exist already or not. This is good (information isn't leaked about who is on the control site). This is bad it's not so easy to use just for one or the other.
The user still needs to make their account when invited with appropriate permissions there.
URLs for emails sent with invites would need to be checked too.

### Group standard add user

Adding an existing site user works on the control site, and permission can be given to the admin. This is done by username auto complete, so listing all the user names on the site.
The form query/validation can be altered to make it work on the microsite itself too (access all users of the site, not just microsite, bypassing the domain entity access)

### Group patch create user

Not looked at this, but just logging here before I loose the link https://www.drupal.org/project/group/issues/2949408

**Comment by msayoung** [comment]
User testing showed that it would be a good idea to streamline this process.

**Comment by finnlewis** [comment]
We should check with a couple of people from the Microsites Working Group if there's an obvious approach that meets their needs.

**Comment by finnlewis** [comment]
See https://github.com/localgovdrupal/localgov_microsites/issues/167

We want to be able to invite users from within the microsite and from the control site.

**Comment by msayoung** [comment]
Ginvite seems to work nicely, in that you can invite people to a microsite from either the Control site or the Microsite

- If the person added doesn't have an account on the control site yet then they are sent a email, and follow a 3 step process. 
- If the person added does already have an account they (can be) sent an email to alert them to accepting the invitatioon

The URLs in the emails are a bit confusing if the email is sent from the control site.

**Comment by msayoung** [comment]
https://github.com/localgovdrupal/localgov_microsites_group/pull/130

**Comment by msayoung** [comment]
Update: we were struggling to write meaningful tests. then this work got sidelined when @finnlewis found some odd behavious outlined on the PR. Not sure what's needed with this now. Assigning to @finnlewis
