### ISSUE TITLE
Accordion does not work when logged out

### ISSUE THREAD

**Issue by finnlewis** [localgovdrupal/localgov_microsites#93]
See https://site1.microsites.localgovdrupal.org/node/1 when logged out - the accordion does not seem to work.

Logged in: 

![Image](https://user-images.githubusercontent.com/326588/169804796-34cb6133-f4ee-42e4-b20f-d103280c4786.png)

![Image](https://user-images.githubusercontent.com/326588/169804833-5ed51953-7ab3-4c53-b3db-a0baaa5b1491.png)

Logged out: 

![Image](https://user-images.githubusercontent.com/326588/169804914-a151de04-08c1-4c76-a65a-3a473a6a35d6.png)

**Comment by finnlewis** [comment]
Not sure @markconroy and @msayoung who's best placed to fix this?

**Comment by markconroy** [comment]
I can take a look

**Comment by markconroy** [comment]
This will be fixed when this PR is merged for subsites

https://github.com/localgovdrupal/localgov_subsites/pull/87
