### ISSUE TITLE
Make summary field optional

### ISSUE THREAD

**Issue by finnlewis** [localgovdrupal/localgov_microsites#95]
@stephen-cox 

On https://localgov-micro-1.lndo.site/node/1/edit

The summary field is required. 

Can we make it optional?

![Image](https://user-images.githubusercontent.com/326588/169812964-a4e46c9d-bfb3-4111-b389-6e2923cf0509.png)

Also @msayoung @richard-s-rowley @markconroy, assumig we keep the summary field, do we want to display the summary field on the node view or not?

**Comment by stephen-cox** [comment]
@finnlewis The summary also displays on teasers. I know we're not using them yet, but this needs to be considered. If we remove the summary what are we going to display on listing pages as such like? I don't think it's same to assume that Pages will never end up in a view

**Comment by finnlewis** [comment]
So you think we should keep it required and display it on the page? I guess that is what the help text says!

**Comment by stephen-cox** [comment]
I think it's fine as it is. It's a design decision to whether it's displayed on the page, but something will be needed for teaser views. If there's no summary to show, what should be displayed instead?

**Comment by msayoung** [comment]
Yes - it's clearer how it should be on the wireframes 

![Image](https://user-images.githubusercontent.com/3852805/169875975-c342d6e0-43ea-4c21-a165-31c6249e767f.png)

I might rework that now (though i'll put that on another ticket)

**Comment by finnlewis** [comment]
For now we keep it required,
